// inhalt/en.js – English help content: lessons, key help and tips (model: fx-991EX).
// Key sequences: [SHIFT][sin]0.5)= …  (see tasten.js). Results use the decimal point. Unlike the German
// fx-991DE X, the English trainer shows no recurring decimals (1÷7 S⇔D → 0.1428571429, not 0.(142857)).

/// Default state: Calculate, MathI/MathO, Degree, Norm 1, Engineer Symbol off
const STANDARD = '[MENU]1[SHIFT][MENU]11[SHIFT][MENU]21[SHIFT][MENU]331[SHIFT][MENU]42[AC]';

export default {
  ui: {
    titel: 'fx-991DE X Trainer · Tom Bleyer',
    hilfe: 'Help',
    tastenhilfe: 'Key help',
    beamer: 'Projector',
    qrschliessen: 'Click or Esc to close',
    lektionen: 'Lessons',
    tasten: 'Keys',
    tipps: 'Tips',
    ueber: 'About',
    schliessen: 'Close',
    lektionenTitel: 'Lessons',
    lektionenIntro: 'Work through the lessons in order. In each step, <b>▶ Show me</b> plays the key sequence on the calculator – the keys light up one after the other. Then you type it yourself and solve the exercises; <b>Check</b> compares your result.',
    uebersicht: 'Overview',
    merke: 'Remember:',
    falle: 'Watch out:',
    aufgaben: 'Exercises',
    aufgabenIntro: 'Work it out on the calculator, then press <b>Check</b>. The result must be showing on the display.',
    vorfuehren: 'Show me',
    anzeige: 'Display:',
    pruefen: 'Check',
    tipp: 'Hint',
    loesungsweg: 'Solution',
    ergebnis: 'Result:',
    richtig: '✓ Correct!',
    nochNicht: '✗ Not yet. Check your input and the settings (D/R at the top of the display, Fix/Sci …).',
    keinErgebnis: 'There is no result on the display right now.',
    tastenTitel: 'Key help',
    tastenIntro: 'Tap a key here – or switch on <b>Key help</b> at the top and tap the calculator directly (press SHIFT or ALPHA first for the second function).',
    taste: 'Key',
    weitere: 'Note',
    tastenhilfeBanner: 'Key help: tap a key → explanation',
    tippsTitel: 'Tips & tricks',
  },

  lektionen: [
    // MARK: Basics
    {
      id: 'start',
      gruppe: 'Basics',
      titel: 'First steps',
      kurz: 'ON, AC/DEL, SHIFT and ALPHA, exact or decimal',
      vorbereitung: STANDARD,
      einleitung: `Each key has up to three functions: <b>white</b> on the key itself (press it directly), <b style="color:#b8860b">yellow</b> above it (first <b>SHIFT</b>, then the key) and <b style="color:#c8102e">red</b> above it (first <b>ALPHA</b>). While SHIFT or ALPHA is active, you see an <b>S</b> or an <b>A</b> at the top of the display.`,
      schritte: [
        { text: '<b>ON</b> switches the calculator on and clears the display. <b>AC</b> clears the whole input, <b>DEL</b> only the character to the left of the cursor.', tasten: '[ON]' },
        { text: '<b>MENU</b> shows all the apps. Press <b>1</b> to choose <i>Calculate</i> – this is where you will do almost all your calculations.', tasten: '[MENU]1' },
        { text: 'A first calculation: 12 + 7 · 3. The calculator follows the order of operations: multiplication before addition.', tasten: '12+7×3=', ergebnis: '33' },
        { text: 'SHIFT followed by the <b>×10ˣ</b> key gives the yellow function π. Here: π · 2.', tasten: '[SHIFT][×10ˣ]×2=', ergebnis: '2π', kette: true },
        { text: 'Whenever possible, results appear in <b>exact</b> form (fraction, root, π). <b>S⇔D</b> switches to a decimal – and back again.', tasten: '[S⇔D]', ergebnis: '6.283185307' },
        { text: 'Correct instead of retyping: <b>◀</b> brings back the last calculation, <b>DEL</b> deletes to the left of the cursor. 12 + 7 · 3 becomes 12 + 7 · 4.', tasten: '12+7×3=[◀][DEL]4=', ergebnis: '40' },
        { text: 'With <b>▲</b> you scroll back through the calculation history to earlier calculations.', tasten: '2+2=3+3=[▲]', ergebnis: '4' },
      ],
      merke: 'White = direct, yellow = SHIFT, red = ALPHA. AC clears everything, DEL one character. S⇔D switches between exact form and decimal.',
      aufgaben: [
        { text: 'Calculate 125 − 4 · 17 + 3.', loesung: '125−4×17+3=', wert: 60 },
        { text: 'Calculate 2π as a decimal.', loesung: '2[SHIFT][×10ˣ]=[S⇔D]', wert: 6.283185307179586, wertText: '6.283185307' },
        { text: 'Calculate (3 + 4) · 5. Then use ◀ to change the calculation to (3 + 4) · 6.', loesung: '(3+4)×5=[◀][DEL]6=', wert: 42 },
      ],
    },
    {
      id: 'schablonen',
      gruppe: 'Basics',
      titel: 'Input as on paper',
      kurz: 'Templates for fraction, root, power – and ▶ to get out again',
      vorbereitung: STANDARD,
      einleitung: 'You enter fractions, roots and powers the way you write them: the key opens a <b>template</b> with boxes. The cursor stays in the box until you leave it with <b>▶</b>.',
      schritte: [
        { text: 'Fraction: <b>▫/▫</b>, type the numerator, <b>▼</b> moves to the denominator, <b>▶</b> takes you out of the fraction.', tasten: '[▫/▫]3[▼]4[▶]+1=', ergebnis: '7/4' },
        { text: 'If you type the number first and then ▫/▫, the number becomes the numerator – the cursor goes straight to the denominator.', tasten: '3[▫/▫]4[▶]+1=', ergebnis: '7/4' },
        { text: 'Square root: <b>√▫</b>. Only ▶ brings the cursor back out from under the root sign: √16 + 9.', tasten: '[√]16[▶]+9=', ergebnis: '13' },
        { text: 'Without ▶, everything stays under the root: √(16 + 9).', tasten: '[√]16+9=', ergebnis: '5' },
        { text: 'Power: <b>x▫</b> raises the exponent; ▶ takes you back down to the baseline: 2⁵ − 1.', tasten: '2[x^]5[▶]−1=', ergebnis: '31' },
        { text: 'Templates can be nested: (√3 + 1)/2.', tasten: '[▫/▫][√]3[▶]+1[▼]2=', ergebnis: '(1+√3)/2' },
      ],
      merke: 'Open the template → fill in the boxes → ▶ to get out. ▲ and ▼ move between numerator and denominator.',
      falle: 'The most common mistake: forgetting ▶. Then the rest of the calculation ends up in the denominator, under the root or in the exponent.',
      aufgaben: [
        { text: 'Calculate 3/8 + 5/12 (result as a fraction).', loesung: '[▫/▫]3[▼]8[▶]+[▫/▫]5[▼]12=', anzeige: '19/24' },
        { text: 'Calculate √50 − √8.', loesung: '[√]50[▶]−[√]8=', anzeige: '3√2', hinweis: 'After √50, press ▶ to leave the root before you type −.' },
        { text: 'Calculate 2³ + 3² using the x▫ key.', loesung: '2[x^]3[▶]+3[x^]2=', wert: 17 },
        { text: 'Calculate the golden ratio (1 + √5)/2 as a decimal.', loesung: '[▫/▫]1+[√]5[▶][▼]2=[S⇔D]', wert: 1.618033988749895, wertText: '1.618033989' },
      ],
    },
    {
      id: 'brueche',
      gruppe: 'Basics',
      titel: 'Fractions and mixed fractions',
      kurz: 'Simplifying, mixed fractions, decimal ↔ fraction, recurring decimals',
      vorbereitung: STANDARD,
      einleitung: 'The calculator simplifies fractions automatically and, whenever possible, shows decimals as fractions. You enter mixed fractions such as 1½ with <b>SHIFT ▫/▫</b>.',
      schritte: [
        { text: 'Simplifying happens automatically: 12/18 =', tasten: '[▫/▫]12[▼]18=', ergebnis: '2/3' },
        { text: 'Mixed fraction: <b>SHIFT ▫/▫</b> opens whole number │ numerator │ denominator. 1½ + 2/3 =', tasten: '[SHIFT][▫/▫]1[▶]1[▼]2[▶]+[▫/▫]2[▼]3=', ergebnis: '13/6', kette: true },
        { text: '<b>SHIFT S⇔D</b> (a b/c ⇔ d/c) converts the improper fraction into a mixed fraction.', tasten: '[SHIFT][S⇔D]', ergebnis: '2 1/6' },
        { text: 'Decimals appear as a fraction if the fraction is short enough:', tasten: '0.75=', ergebnis: '3/4' },
        { text: '<b>S⇔D</b> switches the fraction 1/7 to a decimal. The fx-991EX shows the rounded value 0.1428571429 – without a recurring bar. The German fx-991DE X draws one: 0.<span class="periode">142857</span>.', tasten: '1÷7=[S⇔D]', ergebnis: '0.1428571429' },
        { text: 'Recurring decimal input exists on the German fx-991DE X (this trainer accepts it in every language): after the decimal point, press <b>ALPHA √▫</b> and type the recurring digits. 0.<span class="periode">3</span> =', tasten: '0.[ALPHA][√]3=', ergebnis: '1/3' },
      ],
      merke: 'S⇔D: fraction ⇔ decimal. SHIFT S⇔D: improper fraction ⇔ mixed fraction.',
      aufgaben: [
        { text: 'Calculate 5/6 − 3/4.', loesung: '[▫/▫]5[▼]6[▶]−[▫/▫]3[▼]4=', anzeige: '1/12' },
        { text: 'Calculate 2⅓ · 3/7.', loesung: '[SHIFT][▫/▫]2[▶]1[▼]3[▶]×[▫/▫]3[▼]7=', wert: 1 },
        { text: 'Write 0.125 as a fraction.', loesung: '0.125=', anzeige: '1/8' },
      ],
    },
    {
      id: 'vorrang',
      gruppe: 'Basics',
      titel: 'Order of operations, brackets, negative sign',
      kurz: 'Priority, (−) versus −, multiplication without a sign',
      vorbereitung: STANDARD,
      einleitung: 'The calculator works in a fixed order: brackets and functions first, then powers, then the negative sign, then · and ÷, and finally + and −. If you know this order, you need fewer brackets – and you will not fall into any traps.',
      schritte: [
        { text: 'Multiplication before addition:', tasten: '2+3×4=', ergebnis: '14' },
        { text: 'Brackets first:', tasten: '(2+3)×4=', ergebnis: '20' },
        { text: 'The negative sign <b>(−)</b> is weaker than squaring: −3² = −9.', tasten: '[(−)]3[x²]=', ergebnis: '-9' },
        { text: 'To square −3, put it in brackets: (−3)² = 9.', tasten: '([(−)]3)[x²]=', ergebnis: '9' },
        { text: 'Multiplication <i>without</i> a multiplication sign binds more strongly than ÷: the fx-991 calculates 6 ÷ 2(1 + 2) as 6 ÷ (2 · 3).', tasten: '6÷2(1+2)=', ergebnis: '1' },
        { text: 'Functions open a bracket. Close it: sin(30°) + 1 =', tasten: '[sin]30)+1=', ergebnis: '3/2' },
        { text: 'Without ), the calculator works out sin(30 + 1):', tasten: '[sin]30+1=', ergebnis: '0.5150380749' },
      ],
      merke: '(−) is the negative sign, − means subtraction. For formulas with a fraction bar, use the ▫/▫ template – then there is no doubt about the order.',
      falle: 'For 1 ÷ 2π the calculator works out 1 ÷ (2π). But if you write a ÷ b · c on paper, you may mean (a ÷ b) · c – if in doubt, use brackets!',
      aufgaben: [
        { text: 'Calculate (−2)⁴.', loesung: '([(−)]2)[x^]4=', wert: 16 },
        { text: 'Calculate −2⁴ (without brackets).', loesung: '[(−)]2[x^]4=', wert: -16 },
        { text: 'Calculate (12 − 4)/(2 · 2) using the fraction template.', loesung: '[▫/▫]12−4[▼]2×2=', wert: 2 },
      ],
    },
    {
      id: 'potenzen',
      gruppe: 'Basics',
      titel: 'Powers, roots, powers of ten',
      kurz: 'x², x▫, x⁻¹, √, ∛, scientific notation with ×10ˣ',
      vorbereitung: STANDARD,
      einleitung: 'For very large and very small numbers there is the <b>×10ˣ</b> key: you type 3·10⁸ as <b>3 ×10ˣ 8</b>. Use <b>(−)</b> for negative exponents.',
      schritte: [
        { text: 'Square:', tasten: '5[x²]=', ergebnis: '25' },
        { text: 'Any power with x▫:', tasten: '2[x^]10=', ergebnis: '1024' },
        { text: 'Roots stay exact: √2 · √8 =', tasten: '[√]2[▶]×[√]8=', ergebnis: '4' },
        { text: 'Cube root with SHIFT √▫:', tasten: '[SHIFT][√]27=', ergebnis: '3' },
        { text: 'Reciprocal x⁻¹:', tasten: '4[x⁻¹]=', ergebnis: '1/4' },
        { text: 'Light year: 3·10⁸ m/s · 3600 · 24 · 365 s. Large results are shown with ×10ⁿ.', tasten: '3[×10ˣ]8×3600×24×365=', ergebnis: '9.4608×10^15' },
        { text: 'Two elementary charges: 2 · 1.6·10⁻¹⁹ C.', tasten: '1.6[×10ˣ][(−)]19×2=', ergebnis: '3.2×10^-19' },
      ],
      falle: '<b>10 ×10ˣ 3</b> is 10 · 10³ = 10 000, not 1000. For 10³, type <b>1 ×10ˣ 3</b> (or just ×10ˣ 3).',
      aufgaben: [
        { text: 'Calculate 4.7·10³ · 2.2·10⁻⁶.', loesung: '4.7[×10ˣ]3×2.2[×10ˣ][(−)]6=', wert: 0.01034 },
        { text: 'Calculate 2^0.5. Which exact form does the calculator show?', loesung: '2[x^]0.5=', anzeige: '√2' },
        { text: 'What charge do 5·10¹⁸ electrons carry? Q = 5·10¹⁸ · 1.6·10⁻¹⁹ C', loesung: '5[×10ˣ]18×1.6[×10ˣ][(−)]19=', wert: 0.8 },
      ],
    },

    // MARK: Electrical engineering and physics
    {
      id: 'eng',
      gruppe: 'Electrical engineering and physics',
      titel: 'ENG key and engineering symbols',
      kurz: 'mA, kΩ, µF: results with exponents in steps of three',
      vorbereitung: STANDARD,
      einleitung: 'In electrical engineering you work with k (10³), M (10⁶), m (10⁻³), µ (10⁻⁶), n (10⁻⁹) … The <b>ENG</b> key shows any result as a power of ten whose exponent is a multiple of 3.',
      schritte: [
        { text: 'Current I = U/R with U = 12 V and R = 4.7 kΩ:', tasten: '12÷4.7[×10ˣ]3=', ergebnis: '3/1175', kette: true },
        { text: '<b>ENG</b> shows the result as 2.55·10⁻³ A – that is 2.55 mA.', tasten: '[ENG]', ergebnis: '2.553191489×10^-3', kette: true },
        { text: 'Press <b>ENG</b> again: the exponent goes down by 3 (µA). <b>SHIFT ENG</b> (←) goes the other way.', tasten: '[ENG]', ergebnis: '2553.191489×10^-6' },
        { text: 'Switch on engineering symbols: <b>SHIFT MENU</b> (SETUP) → 4 Engineer Symbol → 1 On.', tasten: '[SHIFT][MENU]41', kette: true },
        { text: 'Now you can enter k, m, µ … via <b>OPTN 3</b> (Engineer Symbol; k is no. 6) – and the result appears with a symbol:', tasten: '12÷4.7[OPTN]36=[S⇔D]', ergebnis: '2.553191489m' },
        { text: 'Resistors in parallel, R = (R₁⁻¹ + R₂⁻¹)⁻¹, with 4.7 kΩ and 10 kΩ:', tasten: '(4.7[OPTN]36[x⁻¹]+10[OPTN]36[x⁻¹])[x⁻¹]=[S⇔D]', ergebnis: '3.197278912k' },
        { text: 'Switch engineering symbols off again: SETUP → 4 → 2 Off.', tasten: '[SHIFT][MENU]42' },
      ],
      merke: 'ENG = exponent in steps of three (k, M, m, µ). SHIFT ENG shifts in the other direction.',
      aufgaben: [
        { text: 'What current flows through 1.2 kΩ at 230 V? (Result in A, e.g. read it with ENG)', loesung: '230÷1.2[×10ˣ]3=[ENG]', wert: 230 / 1200, wertText: '191.6666667×10^-3' },
        { text: 'Power P = U · I with 5 V and 20 mA.', loesung: '5×20[×10ˣ][(−)]3=', wert: 0.1 },
        { text: 'Resistors in series: 2.2 kΩ + 470 Ω + 1 kΩ, in Ω.', loesung: '2.2[×10ˣ]3+470+1[×10ˣ]3=', wert: 3670 },
      ],
    },
    {
      id: 'speicher',
      gruppe: 'Electrical engineering and physics',
      titel: 'Ans, variables and memory M',
      kurz: 'Keep working with intermediate results, STO, RECALL, M+',
      vorbereitung: STANDARD,
      einleitung: '<b>Ans</b> always holds the last result. In the variables <b>A–F, x, y</b> you store values permanently (even after switching off). <b>M</b> is the independent memory for running totals.',
      schritte: [
        { text: 'First calculate …', tasten: '12×5=', ergebnis: '60', kette: true },
        { text: '… then simply continue with ÷: the calculator automatically puts <b>Ans</b> in front.', tasten: '÷4=', ergebnis: '15' },
        { text: 'Storing: the value, then <b>STO</b> and the variable key (A is on (−)). U = 230 V in A:', tasten: '230[STO][(−)]', ergebnis: '230', kette: true },
        { text: 'R = 4.7 kΩ in B (B is on °′″):', tasten: '4.7[×10ˣ]3[STO][°′″]', ergebnis: '4700', kette: true },
        { text: 'Using variables: <b>ALPHA</b> + key. I = A/B:', tasten: '[ALPHA][(−)]÷[ALPHA][°′″]=', ergebnis: '23/470' },
        { text: '<b>SHIFT STO</b> (RECALL) shows all stored values. AC closes the list.', tasten: '[SHIFT][STO]' },
        { text: 'Independent memory: set M to 0 …', tasten: '0[STO][M+]', ergebnis: '0', kette: true },
        { text: '… then add up partial results with <b>M+</b>: 3 · 4.5 …', tasten: '3×4.5[M+]', ergebnis: '27/2', kette: true },
        { text: '… plus 2 · 1.25 …', tasten: '2×1.25[M+]', ergebnis: '5/2', kette: true },
        { text: '… and recall the total (M is the red label on M+):', tasten: '[ALPHA][M+]=', ergebnis: '16' },
        { text: '<b>=</b> repeats the last calculation with the new Ans – ideal for doubling, interest, iterations.', tasten: '1=×2===', ergebnis: '8' },
      ],
      merke: 'Ans = last result. STO + key stores, ALPHA + key recalls. M+ adds, SHIFT M+ (M−) subtracts.',
      aufgaben: [
        { text: 'Store r = 0.5 in A and calculate the area of the circle A²π.', loesung: '0.5[STO][(−)][ALPHA][(−)][x²][SHIFT][×10ˣ]=', anzeige: '1/4π' },
        { text: 'Total price with M+: 3 items at €12, 5 items at €8, 2 items at €15. Recall M at the end.', loesung: '0[STO][M+]3×12[M+]5×8[M+]2×15[M+][ALPHA][M+]=', wert: 106 },
      ],
    },
    {
      id: 'konstanten',
      gruppe: 'Electrical engineering and physics',
      titel: 'Scientific constants and conversions',
      kurz: 'CONST (SHIFT 7) and CONV (SHIFT 8)',
      vorbereitung: STANDARD,
      einleitung: '<b>SHIFT 7</b> (CONST) contains 47 scientific constants in 6 categories, <b>SHIFT 8</b> (CONV) 40 metric conversions. With CONV you type the value first, then the conversion.',
      schritte: [
        { text: 'Open CONST: categories 1 Universal, 2 Electromagnetic, 3 Atomic & Nuclear, 4 Physico-Chem, 5 Adopted Values, 6 Other.', tasten: '[SHIFT]7' },
        { text: 'Speed of light c₀: category 1, no. 3.', tasten: '[SHIFT]713=', ergebnis: '299792458' },
        { text: 'Elementary charge e: category 2, no. 3.', tasten: '[SHIFT]723=', ergebnis: '1.602176634×10^-19' },
        { text: 'Weight of a 75 kg mass: m · g (g: category 5, no. 1). The result appears as a fraction – S⇔D shows the decimal.', tasten: '75×[SHIFT]751=[S⇔D]', ergebnis: '735.49875' },
        { text: 'Converting: 100 km/h to m/s (category 5 Velocity, no. 1).', tasten: '100[SHIFT]851=', ergebnis: '250/9' },
        { text: '25 °C to °F (category 9 Temperature, no. 2).', tasten: '25[SHIFT]892=', ergebnis: '77' },
      ],
      merke: 'CONST: category, then number. CONV: value first, then category and conversion.',
      aufgaben: [
        { text: 'Convert 72 km/h to m/s.', loesung: '72[SHIFT]851=', wert: 20 },
        { text: 'How long does light take to travel from the Sun to the Earth (1.496·10¹¹ m)? t = s/c₀ in s.', loesung: '1.496[×10ˣ]11÷[SHIFT]713=', wert: 1.496e11 / 299792458, wertText: '499.0118049', tol: 1e-9 },
        { text: 'How many kW is 1 hp (category 8 Power, no. 1)?', loesung: '1[SHIFT]881=', wert: 0.745699872 },
      ],
    },
    {
      id: 'trigo',
      gruppe: 'Electrical engineering and physics',
      titel: 'Trigonometry and angle unit',
      kurz: 'Degrees (D) or radians (R), sin/cos/tan, Pol/Rec',
      vorbereitung: STANDARD,
      einleitung: 'At the top of the display you see <b>D</b> (degrees), <b>R</b> (radians) or <b>G</b> (gradians). <i>Always</i> check this before trigonometric calculations! To change it: <b>SHIFT MENU</b> (SETUP) → 2 Angle Unit.',
      schritte: [
        { text: 'Set degrees: SETUP → 2 Angle Unit → 1 Degree.', tasten: '[SHIFT][MENU]21', kette: true },
        { text: 'Exact values: sin 30° =', tasten: '[sin]30)=', ergebnis: '1/2' },
        { text: 'cos 45° =', tasten: '[cos]45)=', ergebnis: '√2/2' },
        { text: 'Inverse function with SHIFT: sin⁻¹(0.5) =', tasten: '[SHIFT][sin]0.5)=', ergebnis: '30' },
        { text: 'Trap: in radians (R), sin 30 means the sine of 30 rad!', tasten: '[SHIFT][MENU]22[sin]30)=', ergebnis: '-0.9880316241', kette: true },
        { text: 'In radians you work with π: sin(π/6) =', tasten: '[sin][▫/▫][SHIFT][×10ˣ][▼]6[▶])=', ergebnis: '1/2' },
        { text: 'Back to degrees. Opposite side = hypotenuse · sin α: 5 · sin 37°', tasten: '[SHIFT][MENU]21 5×[sin]37)=', ergebnis: '3.009075116', kette: true },
        { text: '<b>Pol</b> (SHIFT +) converts coordinates (x, y) into the length r and the angle θ – just like in a phasor diagram.', tasten: '[SHIFT][+]3[SHIFT][)]4)=', ergebnis: 'r=5, θ=53.13010235' },
        { text: 'Angles in degrees, minutes, seconds: convert 1.5° with °′″.', tasten: '1.5=[°′″]', ergebnis: '1°30\'0"' },
      ],
      falle: 'The wrong angle unit is the number one mistake in tests. A quick look at D/R at the top of the display saves you a lot of points.',
      aufgaben: [
        { text: 'Right-angled triangle: adjacent side 8 cm, hypotenuse 10 cm. What is the angle (in degrees)?', loesung: '[SHIFT][MENU]21[SHIFT][cos]8÷10)=', wert: 36.86989764584402, wertText: '36.86989765' },
        { text: 'AC voltage u = 325 V · sin(2π · 50 Hz · 3 ms). Careful: radians!', loesung: '[SHIFT][MENU]22 325[sin]2[SHIFT][×10ˣ]×50×0.003)=', wert: 325 * Math.sin(0.3 * Math.PI), wertText: '262.9305231' },
        { text: 'Adjacent side b = 10 cm · cos 25° (degrees).', loesung: '[SHIFT][MENU]21 10[cos]25)=', wert: 10 * Math.cos(25 * Math.PI / 180), wertText: '9.063077870' },
      ],
    },
    {
      id: 'komplex',
      gruppe: 'Electrical engineering and physics',
      titel: 'Complex numbers and phasors',
      kurz: 'App 2: i, polar form r∠φ, absolute value, impedance',
      vorbereitung: STANDARD + '[MENU]2[SHIFT][MENU][▼]21',
      einleitung: 'In the <b>2 Complex</b> app, the <b>ENG</b> key becomes the imaginary unit <b>i</b> (j in electrical engineering). <b>SHIFT ENG</b> gives the angle sign <b>∠</b> for the polar form r∠φ.',
      schritte: [
        { text: 'Choose the app: MENU → 2.', tasten: '[MENU]2', kette: true },
        { text: 'Calculate as usual: (3 + 4i)(1 − 2i) =', tasten: '(3+4[ENG])(1−2[ENG])=', ergebnis: '11-2i' },
        { text: 'Absolute value (length of the phasor) with SHIFT ( (Abs):', tasten: '[SHIFT][(]3+4[ENG]=', ergebnis: '5' },
        { text: 'Angle (argument) via OPTN → 1 (Argument):', tasten: '[OPTN]1 3+4[ENG])=', ergebnis: '53.13010235' },
        { text: 'Entering polar form: 230∠30° is displayed in rectangular form a + bi.', tasten: '230[SHIFT][ENG]30=', ergebnis: '199.1858429+115i' },
        { text: 'Result in polar form: put <b>OPTN ▼ 1</b> (Polar Coord ▸r∠θ) at the end.', tasten: '3+4[ENG][OPTN][▼]1=', ergebnis: '5∠53.13010235' },
        { text: 'Impedance of an RL series circuit: Z = R + jωL with R = 100 Ω, L = 0.3 H, f = 50 Hz.', tasten: '100+2[SHIFT][×10ˣ]×50×0.3[ENG][OPTN][▼]1=', ergebnis: '137.414133∠43.30380731' },
        { text: 'Current I = U/Z at U = 230 V:', tasten: '230÷(100+30[SHIFT][×10ˣ][ENG])=', ergebnis: '1.218049763-1.147984856i' },
      ],
      merke: 'ENG = i, SHIFT ENG = ∠. OPTN: Argument, Conjugate, Real Part, Imaginary Part, ▸r∠θ, ▸a+bi. In SETUP (page 2) → Complex you choose the default display a+bi or r∠θ.',
      aufgaben: [
        { text: 'Calculate (2 + 3i) + (4 − i).', loesung: '2+3[ENG]+4−[ENG]=', anzeige: '6+2i' },
        { text: 'Calculate the absolute value of −6 + 8i.', loesung: '[SHIFT][(][(−)]6+8[ENG]=', wert: 10 },
        { text: 'Enter the phasor 10∠90°. What does the calculator show?', loesung: '10[SHIFT][ENG]90=', anzeige: '10i' },
        { text: 'Convert Z = 50 − 80i to polar form.', loesung: '50−80[ENG][OPTN][▼]1=', anzeige: '10√89∠-57.99461679', hinweis: 'The absolute value √8900 = 10√89 stays exact; S⇔D shows 94.34∠−57.99.' },
      ],
    },

    // MARK: Tools
    {
      id: 'calc',
      gruppe: 'Tools',
      titel: 'Formulas with CALC, equations with SOLVE',
      kurz: 'Type a formula once, substitute values, solve for any quantity',
      vorbereitung: STANDARD,
      einleitung: '<b>CALC</b> asks for each variable in turn and evaluates the formula – handy for a series of measurements. <b>SOLVE</b> (SHIFT CALC) solves an equation for one variable (Newton’s method with an initial value). The equals sign is <b>ALPHA CALC</b>.',
      schritte: [
        { text: 'P = U²/R: type the formula with A (= U) and B (= R), press <b>CALC</b>, enter the values (= after each one).', tasten: '[▫/▫][ALPHA][(−)][x²][▼][ALPHA][°′″][CALC]230=1000=', ergebnis: '529/10', kette: true },
        { text: 'Press <b>CALC</b> again – new values, same formula: 12 V across 4.7 Ω.', tasten: '[CALC]12=4.7=', ergebnis: '1440/47' },
        { text: 'SOLVE: x² − 5x + 6 = 0 with initial value 0. The “=” is ALPHA CALC. After SHIFT CALC: type the initial value, press =, and = once more to solve.', tasten: '[x][x²]−5[x]+6[ALPHA][CALC]0[SHIFT][CALC]0==', ergebnis: 'x=2;L−R=0', kette: true },
        { text: 'You find the second solution with a different initial value (5).', tasten: '[SHIFT][CALC]5==', ergebnis: 'x=3;L−R=0' },
        { text: 'Rearranging a formula without algebra: which resistance draws exactly 60 W at 230 V? Pressing AC twice leaves SOLVE. Then 60 = 230²/B, initial value 100.', tasten: '[AC][AC]60[ALPHA][CALC][▫/▫]230[x²][▼][ALPHA][°′″][SHIFT][CALC]100==', ergebnis: 'B=881.6666667;L−R=0' },
      ],
      merke: 'CALC: substitute values (▼ skips a variable). SOLVE: enter an initial value, then =. L−R = 0 (left side minus right side) means the solution is correct.',
      falle: 'SOLVE only ever finds <i>one</i> solution – the one closest to the initial value. For other solutions, change the initial value.',
      aufgaben: [
        { text: 'Use CALC to calculate the area of a circle πx² for x = 3.', loesung: '[SHIFT][×10ˣ][x][x²][CALC]3=', anzeige: '9π' },
        { text: 'U = R · I: use CALC to calculate the voltage for R = 470 Ω and I = 0.02 A (formula A·B).', loesung: '[ALPHA][(−)][ALPHA][°′″][CALC]470=0.02=', wert: 9.4 },
        { text: 'Solve 2ˣ = 10 with SOLVE (initial value 1).', loesung: '2[x^][x][▶][ALPHA][CALC]10[SHIFT][CALC]1==', variable: 'x', wert: Math.log2(10), wertText: '3.321928095' },
      ],
    },
    {
      id: 'gleichungen',
      gruppe: 'Tools',
      titel: 'Simultaneous equations and polynomials',
      kurz: 'App A: linear systems with up to 4 unknowns, quadratic and cubic equations',
      vorbereitung: STANDARD,
      einleitung: 'In the <b>A Equation/Func</b> app (MENU, then the (−) key for A) you only enter the coefficients. <b>1</b> = Simul Equation, <b>2</b> = Polynomial. Confirm each value with =; one more = solves, and each further = shows the next solution.',
      schritte: [
        { text: 'x + 2y = 3 and 2x + 3y = 4: MENU A → 1 → 2 unknowns, coefficients row by row.', tasten: '[MENU][(−)]12 1=2=3=2=3=4==', ergebnis: 'x=-1', kette: true },
        { text: 'Press = (or ▼) for the next solution:', tasten: '=', ergebnis: 'y=2' },
        { text: 'Kirchhoff’s laws: I₁ − I₂ − I₃ = 0, 100I₁ + 220I₂ = 12, 220I₂ − 330I₃ = 0 (3 unknowns; x = I₁).', tasten: '[MENU][(−)]13 1=[(−)]1=[(−)]1=0=100=220=0=12=0=220=[(−)]330=0==', ergebnis: 'x=3/58' },
        { text: 'Quadratic equation x² + 2x − 2 = 0: MENU A → 2 → degree 2.', tasten: '[MENU][(−)]22 1=2=[(−)]2==', ergebnis: 'x₁=-1+√3', kette: true },
        { text: 'Second solution, then the vertex (x- and y-value of the minimum):', tasten: '=', ergebnis: 'x₂=-1-√3' },
        { text: 'Cubic equation x³ − 6x² + 11x − 6 = 0:', tasten: '[MENU][(−)]23 1=[(−)]6=11=[(−)]6==', ergebnis: 'x₁=3' },
        { text: 'No real solution? Then complex solutions appear: x² + 1 = 0.', tasten: '[MENU][(−)]22 1=0=1==', ergebnis: 'x₁=i' },
      ],
      merke: 'First bring the equation into standard form (… = 0) and enter 0 for missing terms. AC in the editor sets all coefficients to 0.',
      aufgaben: [
        { text: 'Solve 2x − y = 1 and x + y = 5. What is x?', loesung: '[MENU][(−)]12 2=[(−)]1=1=1=1=5==', anzeige: 'x=2' },
        { text: 'Solve 2x² − 3x − 2 = 0. What is x₁?', loesung: '[MENU][(−)]22 2=[(−)]3=[(−)]2==', anzeige: 'x₁=2' },
        { text: 'Vertex of y = x² − 6x + 5: what is the y-value of the minimum?', loesung: '[MENU][(−)]22 1=[(−)]6=5=====', anzeige: 'y=-4' },
      ],
    },
    {
      id: 'tabelle',
      gruppe: 'Tools',
      titel: 'Tables of values',
      kurz: 'App 9: f(x) and g(x), Start, End, Step',
      vorbereitung: STANDARD,
      einleitung: 'In the <b>9 Table</b> app you type f(x) (x with the <b>x</b> key), g(x) if you want, then Start, End and Step. Use ▲▼ to move through the table; in the x column you can overwrite values.',
      schritte: [
        { text: 'f(x) = x² − 2x − 3 from −2 to 4: type f, =, leave g empty (=), then Start −2, End 4, Step 1 and = once more.', tasten: '[MENU]9[x][x²]−2[x]−3==[(−)]2=4=1==' },
        { text: 'Where does f change sign? Scroll down with ▼: zeros at x = −1 and x = 3.', tasten: '[▼][▼][▼][▼][▼]' },
        { text: 'Comparing two functions: f(x) = x², g(x) = 2x + 3. The values are equal at x = 3.', tasten: '[MENU]9[x][x²]=2[x]+3=0=4=1==' },
      ],
      merke: 'AC takes you back to the function input. The table has at most 30 rows (with g) or 45 rows (f only).',
      aufgaben: [
        { text: 'Calculate f(1.5) for f(x) = x² − 2x − 3 using CALC in the Calculate app.', loesung: '[MENU]1[x][x²]−2[x]−3[CALC]1.5=', wert: -3.75 },
      ],
    },
    {
      id: 'statistik',
      gruppe: 'Tools',
      titel: 'Statistics and regression',
      kurz: 'App 6: mean, standard deviation, line of best fit',
      vorbereitung: STANDARD,
      einleitung: 'In the <b>6 Statistics</b> app you choose the type (1 = 1-Variable, 2 = y=a+bx …) and type the data into the editor (= after each value). <b>AC</b> takes you to the calculation screen, <b>OPTN</b> to the statistical values.',
      schritte: [
        { text: 'Five measured values: 4.8, 5.1, 5.0, 4.9 and 5.2 V.', tasten: '[MENU]61 4.8=5.1=5=4.9=5.2=', kette: true },
        { text: '<b>AC</b>, then <b>OPTN 2</b> (1-Variable Calc) shows all the statistical values (▲▼ scrolls).', tasten: '[AC][OPTN]2', ergebnis: 'x̄=5;Σx=25;Σx²=125.1;σ²x=0.02' },
        { text: 'Single values for calculations: OPTN ▼ 2 (Variable) → 4 = σx (standard deviation).', tasten: '[AC][OPTN][▼]24=', ergebnis: '0.1414213562' },
        { text: 'Regression: U-I characteristic of a resistor. Type 2 (y=a+bx), x = U, y = I.', tasten: '[MENU]62 2=4=6=8=[▶][▲][▲][▲][▲]0.0042=0.0085=0.0128=0.017=', kette: true },
        { text: 'Slope b = I/U via OPTN ▼ 4 (Regression) → 2 (b):', tasten: '[AC][OPTN][▼]42=[S⇔D]', ergebnis: '2.135×10^-3', kette: true },
        { text: 'The resistance is the reciprocal of the slope: R = 1/b.', tasten: '[x⁻¹]=[S⇔D]', ergebnis: '468.3840749' },
      ],
      merke: 'σx: population standard deviation of the measured values, sx: sample standard deviation. For regressions, r shows how good the fit is (|r| close to 1 = very good).',
      aufgaben: [
        { text: 'Mean of 12, 15, 11, 14, 13?', loesung: '[MENU]61 12=15=11=14=13=[AC][OPTN][▼]22=', wert: 13 },
        { text: 'Sample standard deviation sx of the same data (OPTN ▼ 2 → 6)?', loesung: '[MENU]61 12=15=11=14=13=[AC][OPTN][▼]26=', wert: Math.sqrt(2.5), wertText: '1.58113883' },
      ],
    },
    {
      id: 'analysis',
      gruppe: 'Tools',
      titel: 'Integral, derivative, sum',
      kurz: '∫, d/dx and Σ – numerical and fast',
      vorbereitung: STANDARD,
      einleitung: 'The <b>∫▫▫</b> key calculates definite integrals, <b>SHIFT ∫</b> (d/dx) the derivative at a point, <b>SHIFT x</b> (Σ) sums. Order of the boxes: function → lower limit → upper limit (▶ moves on).',
      schritte: [
        { text: '∫₀² x² dx:', tasten: '[∫][x][x²][▶]0[▶]2=', ergebnis: '8/3' },
        { text: 'Area under one arch of the sine curve from 0 to π – with trigonometric functions, always use <b>radians</b>!', tasten: '[SHIFT][MENU]22[∫][sin][x])[▶]0[▶][SHIFT][×10ˣ]=', ergebnis: '2' },
        { text: 'Derivative of x³ at x = 2 (d/dx = SHIFT ∫):', tasten: '[SHIFT][MENU]21[SHIFT][∫][x][x^]3[▶][▶]2=', ergebnis: '12' },
        { text: 'Sum 1 + 2 + … + 10 with Σ (SHIFT x):', tasten: '[SHIFT][x][x][▶]1[▶]10=', ergebnis: '55' },
      ],
      falle: 'Only use sin, cos, tan in ∫ and d/dx in radians (R) – otherwise the results are wrong.',
      aufgaben: [
        { text: 'Calculate ∫₁³ (2x + 1) dx.', loesung: '[∫]2[x]+1[▶]1[▶]3=', wert: 10 },
        { text: 'What is the derivative of √x at x = 4?', loesung: '[SHIFT][∫][√][x][▶][▶]4=', wert: 0.25 },
        { text: 'RMS value of a sinusoidal voltage with û = 325 V: U = √( 1/(2π) · ∫₀^2π (325 sin x)² dx ) (radians).', loesung: '[SHIFT][MENU]22[√][▫/▫]1[▼]2[SHIFT][×10ˣ][▶][∫](325[sin][x]))[x²][▶]0[▶]2[SHIFT][×10ˣ]=', wert: 325 / Math.SQRT2, wertText: '229.8097039', tol: 1e-8 },
      ],
    },
    {
      id: 'basisn',
      gruppe: 'Tools',
      titel: 'Number systems (digital electronics)',
      kurz: 'App 3: DEC, HEX, BIN, OCT, and/or/not',
      vorbereitung: STANDARD,
      einleitung: 'In the <b>3 Base-N</b> app you calculate with integers (32 bits). The blue labels apply: <b>x²</b> = DEC, <b>x▫</b> = HEX, <b>log</b> = BIN, <b>ln</b> = OCT. The hex digits A–F are on the keys (−) to tan.',
      schritte: [
        { text: 'Choose app 3 (it starts in DEC).', tasten: '[MENU]3', kette: true },
        { text: 'Enter 255 …', tasten: '255=', ergebnis: '255', kette: true },
        { text: '… and show it in hexadecimal with HEX (x▫ key):', tasten: '[x^]', ergebnis: '000000FF' },
        { text: 'Binary arithmetic: BIN (log key), then 1011 + 110.', tasten: '[log]1011+110=', ergebnis: '0000 0000 0000 0000/0000 0000 0001 0001', kette: true },
        { text: 'Logical AND via OPTN → 1 (and): 1100 and 1010.', tasten: '1100[OPTN]1 1010=', ergebnis: '0000 0000 0000 0000/0000 0000 0000 1000', kette: true },
        { text: 'Show it in decimal (x² key):', tasten: '[x²]', ergebnis: '8' },
      ],
      merke: 'You can switch the number system at any time with the blue keys – even for the result currently on the display.',
      aufgaben: [
        { text: 'What is 200 (decimal) in hexadecimal?', loesung: '[MENU]3[x²]200=[x^]', anzeige: '000000C8' },
        { text: 'Which decimal number is 1111 (binary)?', loesung: '[MENU]3[log]1111=[x²]', wert: 15 },
      ],
    },
    {
      id: 'fehler',
      gruppe: 'Tools',
      titel: 'Error detective',
      kurz: 'Math ERROR, Syntax ERROR, wrong angle unit, Fix, RESET',
      vorbereitung: STANDARD,
      einleitung: 'Error messages are no drama: <b>AC</b> clears, <b>◀</b> or <b>▶</b> takes you back to your input so you can correct it.',
      schritte: [
        { text: '<b>Math ERROR</b>: division by 0, square root of a negative number, result too large …', tasten: '5÷0=', ergebnis: 'Math ERROR' },
        { text: '<b>Syntax ERROR</b>: the input is not a valid expression, e.g. two operators in a row.', tasten: '5×÷2=', ergebnis: 'Syntax ERROR', kette: true },
        { text: 'Use ◀ to go back to the input, remove the mistake with DEL, calculate again.', tasten: '[◀][◀][◀][DEL][▶][▶]=', ergebnis: '5/2', kette: true },
        { text: 'Strange trigonometric values? Check the angle unit! Here the calculator is set to R:', tasten: '[SHIFT][MENU]22[sin]30)=', ergebnis: '-0.9880316241' },
        { text: 'Too few decimal places? Maybe Fix is set (FIX at the top of the display). Fix 2:', tasten: '[SHIFT][MENU]21[SHIFT][MENU]312 1÷3[SHIFT]=', ergebnis: '0.33', kette: true },
        { text: 'Back to Norm 1: SETUP → 3 Number Format → 3 Norm → 1.', tasten: '[SHIFT][MENU]331 1÷3[SHIFT]=', ergebnis: '0.3333333333' },
        { text: 'If nothing else helps: <b>SHIFT 9</b> (RESET) → 3 Initialize All → = → AC.', tasten: '[SHIFT]93=[AC]' },
      ],
      merke: 'Before every test, check quickly: app 1 (Calculate), D at the top of the display, no FIX/SCI.',
      aufgaben: [
        { text: 'A classmate types sin 30 + 15 without the closing bracket. What does the calculator show (degrees)?', loesung: '[sin]30+15=', anzeige: '√2/2', hinweis: 'Without ), the calculator works out sin(30 + 15) = sin 45°.' },
        { text: 'Someone wants to calculate 1/(2 · 5) and types 1 ÷ 2 × 5. Calculate the correct value with the fraction template.', loesung: '[▫/▫]1[▼]2×5=', wert: 0.1 },
      ],
    },
  ],

  // MARK: Key help

  tasten: {
    shift: { name: 'SHIFT', haupt: 'Activates the <b style="color:#b8860b">yellow</b> label of the next key. <b>S</b> appears on the display. Press it again to cancel SHIFT.' },
    alpha: { name: 'ALPHA', haupt: 'Activates the <b style="color:#c8102e">red</b> label of the next key: variables A–F, x, y, M as well as =, : and i. <b>A</b> appears on the display.' },
    menu: { name: 'MENU', haupt: 'Main menu with all apps (1 Calculate … D Ratio). Select with the number or letter key, or with the cursor keys and =.', shift: '<b>SETUP</b>: settings – Input/Output, Angle Unit, Number Format, Engineer Symbol, Fraction Result, Complex, Decimal Mark … (▼ turns the page).' },
    on: { name: 'ON', haupt: 'Switches on. Clears the display and the history; variables and settings are kept.' },
    up: { name: '▲', haupt: 'In fractions: from the denominator to the numerator. With no input: back through the history to earlier calculations. In menus and lists: up.' },
    down: { name: '▼', haupt: 'In fractions: from the numerator to the denominator. In the history: forwards. In menus: to the next page; in lists: down.' },
    left: { name: '◀', haupt: 'Moves the cursor left. After a result: edit the last calculation (cursor at the end).' },
    right: { name: '▶', haupt: 'Moves the cursor right – and <b>out of a template</b> (fraction, root, power). After a result: edit the calculation (cursor at the start).' },
    optn: { name: 'OPTN', haupt: 'Extra functions of the current app, e.g. in Calculate: Hyperbolic Func, Angle Unit (°, r, g), Engineer Symbol (k, m, µ …). In Complex: Argument, Conjugate, ▸r∠θ. In Statistics: the statistical values.', shift: '<b>QR</b>: shows the QR code of this trainer on the display (on the real calculator: a link to the CASIO website).' },
    calc: { name: 'CALC', haupt: 'Evaluates a formula with variables: asks for each variable (value, =) and calculates. Press CALC again for new values.', shift: '<b>SOLVE</b>: solves an equation for one variable (enter an initial value, then =).', alpha: '<b>=</b> as the equals sign in equations (for SOLVE, CALC, Verify).' },
    int: { name: '∫▫▫', haupt: 'Definite integral: function, lower and upper limit (▶ moves on).', shift: '<b>d/dx</b>: derivative of a function at a point.', alpha: '<b>:</b> separates several calculations, which = then carries out one after the other.' },
    x: { name: 'x', haupt: 'The variable x (for functions, CALC, SOLVE, tables).', shift: '<b>Σ</b>: sum of an expression in x from a start value to an end value.' },
    frac: { name: '▫/▫', haupt: 'Fraction template. If a number comes before it, that number becomes the numerator.', shift: 'Mixed fraction (whole number, numerator, denominator).' },
    sqrt: { name: '√▫', haupt: 'Square root. ▶ takes you out from under the root sign.', shift: '∛: cube root.', alpha: 'Enters a recurring decimal (fx-991DE X; this trainer accepts it in every language), e.g. 0.1, then ALPHA √ 6 for 0.1<span class="periode">6</span>.' },
    sq: { name: 'x²', haupt: 'Square of the preceding value.', shift: 'x³: cube.', extra: 'In the Base-N app (blue): <b>DEC</b>, decimal system.' },
    pow: { name: 'x▫', haupt: 'Any power: the exponent is entered raised (▶ takes you back).', shift: '▫√▫: nth root.', extra: 'Base-N: <b>HEX</b>.' },
    log: { name: 'log▫▫', haupt: 'Logarithm to any base: log₂(16) = 4.', shift: '10▫: power of ten 10ˣ.', extra: 'Base-N: <b>BIN</b>.' },
    ln: { name: 'ln', haupt: 'Natural logarithm (base e).', shift: 'e▫: exponential function eˣ.', extra: 'Base-N: <b>OCT</b>.' },
    neg: { name: '(−)', haupt: 'Negative sign (not the minus key!). −3² = −9, but (−3)² = 9.', shift: '<b>log(</b>: common logarithm (base 10); with a comma also log(a, b) to base a.', alpha: 'Variable <b>A</b>.', extra: 'Base-N (HEX): digit A.' },
    dms: { name: '°′″', haupt: 'Enters degrees, minutes, seconds (press it after each part). Applied to a result: converts decimal ⇔ °′″.', shift: '<b>FACT</b>: prime factorization of the result.', alpha: 'Variable <b>B</b>.' },
    inv: { name: 'x⁻¹', haupt: 'Reciprocal 1/x. For matrices: inverse.', shift: 'x!: factorial.', alpha: 'Variable <b>C</b>.' },
    sin: { name: 'sin', haupt: 'Sine – watch the angle unit D/R/G!', shift: 'sin⁻¹ (arcsin): the angle for a given sine value.', alpha: 'Variable <b>D</b>.' },
    cos: { name: 'cos', haupt: 'Cosine.', shift: 'cos⁻¹ (arccos).', alpha: 'Variable <b>E</b>.' },
    tan: { name: 'tan', haupt: 'Tangent.', shift: 'tan⁻¹ (arctan).', alpha: 'Variable <b>F</b>.' },
    sto: { name: 'STO', haupt: 'Store: puts a value (or result) into a variable – STO, then the variable key (without ALPHA).', shift: '<b>RECALL</b>: shows all variables; a variable key inserts that variable into the calculation.' },
    eng: { name: 'ENG', haupt: 'Shows the result in engineering notation (exponent a multiple of 3); pressing it again shifts by 10³.', shift: '←: engineering notation in the opposite direction. In the Complex app: <b>∠</b> (polar form).', extra: 'In the Complex app, ENG is the imaginary unit <b>i</b>.' },
    lpar: { name: '(', haupt: 'Opening bracket.', shift: '<b>Abs</b>: absolute value |▫|.' },
    rpar: { name: ')', haupt: 'Closing bracket (also closes sin(, log( …).', shift: 'Separator for functions with several arguments, e.g. Pol(3, 4): a comma (a semicolon when the Decimal Mark is set to Comma).', alpha: 'Variable <b>x</b>.' },
    sd: { name: 'S⇔D', haupt: 'Toggles the result: exact form (fraction, root, π) ⇔ decimal (the German fx-991DE X also shows recurring decimals).', shift: 'a b/c ⇔ d/c: mixed fraction ⇔ improper fraction.', alpha: 'Variable <b>y</b>.' },
    mplus: { name: 'M+', haupt: 'Adds the result to memory M (M appears at the top).', shift: 'M−: subtracts from memory M.', alpha: 'Memory <b>M</b> as a variable.' },
    7: { name: '7', haupt: 'Digit 7.', shift: '<b>CONST</b>: 47 scientific constants.' },
    8: { name: '8', haupt: 'Digit 8.', shift: '<b>CONV</b>: 40 metric conversions.' },
    9: { name: '9', haupt: 'Digit 9.', shift: '<b>RESET</b>: resets Setup Data, Variable/Memory or everything (Initialize All).' },
    del: { name: 'DEL', haupt: 'Deletes the character to the left of the cursor.', shift: '<b>INS</b>: the next template encloses the expression to the right of the cursor.', alpha: '<b>UNDO</b>: undoes the last change.' },
    ac: { name: 'AC', haupt: 'Clears the whole input, or closes menus and error messages.', shift: '<b>OFF</b>: switches off (memory is kept).' },
    mul: { name: '×', haupt: 'Multiplication.', shift: '<b>nPr</b>: permutations.' },
    div: { name: '÷', haupt: 'Division.', shift: '<b>nCr</b>: combinations (binomial coefficient).' },
    add: { name: '+', haupt: 'Addition.', shift: '<b>Pol(x, y)</b>: rectangular → polar (r, θ).' },
    sub: { name: '−', haupt: 'Subtraction (for negative numbers use the (−) key).', shift: '<b>Rec(r, θ)</b>: polar → rectangular (x, y).' },
    0: { name: '0', haupt: 'Digit 0.', shift: '<b>Rnd(</b>: rounds to the current Number Format (Fix/Sci).' },
    dot: { name: 'Decimal point', haupt: 'Decimal point (SETUP → Decimal Mark switches between Dot and Comma).', shift: '<b>Ran#</b>: random number 0.000 … 0.999.', alpha: '<b>RanInt#(a, b)</b>: random integer from a to b (dice: 1, 6).' },
    exp: { name: '×10ˣ', haupt: 'Power of ten for scientific notation: 1.6 ×10ˣ (−) 19.', shift: '<b>π</b>', alpha: '<b>e</b> (Euler’s number)' },
    ans: { name: 'Ans', haupt: 'The last result.', shift: '<b>%</b>: percent (150 × 20% = 30).' },
    eq: { name: '=', haupt: 'Carries out the calculation. Pressing = again repeats the last calculation with the new Ans.', shift: '<b>≈</b>: shows the result directly as a decimal.' },
  },

  // MARK: Tips

  tipps: [
    { titel: 'Ans comes automatically', text: 'After a result, every operation (+ − × ÷ x² …) automatically starts with Ans. So you do not need to type Ans.', tasten: '20=÷4=' },
    { titel: '= repeats', text: 'When a result is on the display, = repeats the last calculation with the new Ans – handy for compound interest or iterations.', tasten: '1000=×1.05===' },
    { titel: 'Edit instead of retyping', text: '◀ brings back the last calculation, ▲ older ones. Change it, press = – done.' },
    { titel: 'Decimal straight away', text: 'SHIFT = (≈) shows the result directly as a decimal; S⇔D switches back and forth at any time.', tasten: '1÷3[SHIFT]=' },
    { titel: 'Close your brackets', text: 'sin(, cos(, log( … open a bracket. If you forget ), the rest of the calculation becomes part of the argument.' },
    { titel: 'Fraction template for formulas', text: 'For formulas with a fraction bar (e.g. R = U/I, resistors in parallel), use the ▫/▫ template – then the order is always right.' },
    { titel: 'D or R?', text: 'The letter at the top of the display shows the angle unit: D = degrees, R = radians. For ∫ and d/dx with trigonometric functions, set R.' },
    { titel: 'Several calculations at once', text: 'ALPHA ∫ gives a colon. Each = shows the next partial result (Disp at the top of the display).', tasten: '3+3[ALPHA][∫]3×3==' },
    { titel: 'Undo', text: 'ALPHA DEL (UNDO) undoes the last change to your input.' },
    { titel: 'On a computer', text: 'Keyboard: digits, + − * / ^ ( ), Enter = “=”, Backspace = DEL, Esc = AC, arrow keys. Q shows the QR code full screen.' },
    { titel: 'Install as an app', text: 'iPhone/iPad: in Safari, Share → “Add to Home Screen”. Android: menu → “Install app”. After that, the trainer also works offline.' },
  ],

  ueber: `<h2>fx-991DE X Trainer</h2>
<p>A practice calculator for the classroom, modelled on the <b>CASIO fx-991DE X</b> scientific calculator (ClassWiz): the same key layout, natural textbook input and exact results – so you can practise using your calculator on your phone or on the projector, too. In English, the trainer behaves like the international <b>fx-991EX</b>: decimal point, no recurring decimals.</p>
<p>Included: Calculate, Complex, Base-N, Matrix, Vector, Statistics, Distribution, Table, Equation/Func, Inequality, Verify and Ratio. Not included: Spreadsheet.</p>
<p class="gedaempft">A learning project by <b>Tom Bleyer</b> (LTEtt, electrical engineering). Not a CASIO product. CASIO, ClassWiz and fx-991 are trademarks of CASIO Computer Co., Ltd. In some cases, results may differ from what the real calculator displays.</p>
<p class="gedaempft">Source code (MIT License): <a href="https://github.com/temmchen/fx991">github.com/temmchen/fx991</a></p>`,
};
