// inhalt/fr.js – Contenu d'aide en français (modèle : fx-991DE X) : leçons, aide des touches, astuces.
// Séquences de touches : [SHIFT][sin]0.5)= …  (voir tasten.js). Résultats avec le point comme séparateur
// décimal (l'aide les affiche avec le séparateur réglé) ; nombres périodiques notés 0.(3).
// Les champs techniques (tasten, loesung, ergebnis, wert …) sont identiques à de.js, sauf l'écran SOLVE :
// en français, la calculatrice y affiche G−D (gauche − droite) au lieu de L−R.

/// État de départ : Calculs, MathE/MathS, degrés, Norm 1, symboles ingénieur désactivés
const STANDARD = '[MENU]1[SHIFT][MENU]11[SHIFT][MENU]21[SHIFT][MENU]331[SHIFT][MENU]42[AC]';

export default {
  ui: {
    titel: 'fx-991DE X Trainer · Tom Bleyer',
    hilfe: "Aide",
    tastenhilfe: "Aide touches",
    beamer: "Projecteur",
    qrschliessen: "Clic ou Échap pour fermer",
    lektionen: "Leçons",
    tasten: "Touches",
    tipps: "Astuces",
    ueber: "À propos",
    schliessen: "Fermer",
    lektionenTitel: "Leçons",
    lektionenIntro: "Travaille les leçons dans l'ordre. À chaque étape, <b>▶ Montrer</b> joue la séquence de touches sur la calculatrice – les touches s'allument l'une après l'autre. Ensuite, tu tapes toi-même et tu résous les exercices ; <b>Vérifier</b> compare ton résultat.",
    uebersicht: "Sommaire",
    merke: "À retenir :",
    falle: "Attention :",
    aufgaben: "Exercices",
    aufgabenIntro: "Calcule sur la calculatrice, puis appuie sur <b>Vérifier</b>. Le résultat doit alors être affiché à l'écran.",
    vorfuehren: "Montrer",
    anzeige: "Affichage :",
    pruefen: "Vérifier",
    tipp: "Indice",
    loesungsweg: "Solution",
    ergebnis: "Résultat :",
    richtig: "✓ Correct !",
    nochNicht: "✗ Pas encore. Vérifie ta saisie et les réglages (D/R en haut de l'écran, Fix/Sci …).",
    keinErgebnis: "Aucun résultat n'est affiché à l'écran pour l'instant.",
    tastenTitel: "Aide touches",
    tastenIntro: "Appuie ici sur une touche – ou active <b>Aide touches</b> en haut et appuie directement sur les touches de la calculatrice (d'abord SHIFT ou ALPHA pour la deuxième fonction).",
    taste: "Touche",
    weitere: "Remarque",
    tastenhilfeBanner: "Aide touches : appuie sur une touche → explication",
    tippsTitel: "Trucs & astuces",
  },

  lektionen: [
    // MARK: Bases
    {
      id: 'start',
      gruppe: "Bases",
      titel: "Premiers pas",
      kurz: "ON, AC/DEL, SHIFT et ALPHA, valeur exacte ou nombre décimal",
      vorbereitung: STANDARD,
      einleitung: `Chaque touche a jusqu'à trois fonctions : en <b>blanc</b> sur la touche (directement), en <b style="color:#b8860b">jaune</b> au-dessus (d'abord <b>SHIFT</b>, puis la touche) et en <b style="color:#c8102e">rouge</b> au-dessus (d'abord <b>ALPHA</b>). Tant que SHIFT ou ALPHA est actif, tu vois un <b>S</b> ou un <b>A</b> en haut de l'écran.`,
      schritte: [
        { text: "<b>ON</b> allume la calculatrice et efface l'écran. <b>AC</b> efface toute la saisie, <b>DEL</b> seulement le caractère à gauche du curseur.", tasten: '[ON]' },
        { text: "<b>MENU</b> affiche toutes les applications. Avec <b>1</b>, tu choisis <i>Calculs</i> – c'est là que tu calcules presque toujours.", tasten: '[MENU]1' },
        { text: "Un premier calcul : 12 + 7 · 3. La calculatrice respecte la priorité des opérations : × et ÷ avant + et −.", tasten: '12+7×3=', ergebnis: '33' },
        { text: "SHIFT puis la touche <b>×10ˣ</b> donnent la fonction jaune π. Ici : π · 2.", tasten: '[SHIFT][×10ˣ]×2=', ergebnis: '2π', kette: true },
        { text: "Les résultats s'affichent si possible sous forme <b>exacte</b> (fraction, racine, π). <b>S⇔D</b> passe au nombre décimal – et inversement.", tasten: '[S⇔D]', ergebnis: '6.283185307' },
        { text: "Corriger au lieu de tout retaper : <b>◀</b> rappelle le dernier calcul, <b>DEL</b> efface à gauche du curseur. 12 + 7 · 3 devient 12 + 7 · 4.", tasten: '12+7×3=[◀][DEL]4=', ergebnis: '40' },
        { text: "Avec <b>▲</b>, tu remontes dans l'historique vers les calculs plus anciens.", tasten: '2+2=3+3=[▲]', ergebnis: '4' },
      ],
      merke: "Blanc = direct, jaune = SHIFT, rouge = ALPHA. AC efface tout, DEL un seul caractère. S⇔D bascule entre valeur exacte et nombre décimal.",
      aufgaben: [
        { text: "Calcule 125 − 4 · 17 + 3.", loesung: '125−4×17+3=', wert: 60 },
        { text: "Calcule 2π sous forme de nombre décimal.", loesung: '2[SHIFT][×10ˣ]=[S⇔D]', wert: 6.283185307179586, wertText: '6.283185307' },
        { text: "Calcule (3 + 4) · 5. Ensuite, avec ◀, transforme le calcul en (3 + 4) · 6.", loesung: '(3+4)×5=[◀][DEL]6=', wert: 42 },
      ],
    },
    {
      id: 'schablonen',
      gruppe: "Bases",
      titel: "Saisie comme dans le cahier",
      kurz: "Gabarits pour fraction, racine, puissance – et ▶ pour en sortir",
      vorbereitung: STANDARD,
      einleitung: "Les fractions, les racines et les puissances se saisissent comme tu les écris : la touche ouvre un <b>gabarit</b> avec des cases. Le curseur reste dans la case jusqu'à ce que tu en sortes avec <b>▶</b>.",
      schritte: [
        { text: "Fraction : <b>▫/▫</b>, tape le numérateur, <b>▼</b> pour descendre au dénominateur, <b>▶</b> pour sortir de la fraction.", tasten: '[▫/▫]3[▼]4[▶]+1=', ergebnis: '7/4' },
        { text: "Si tu tapes d'abord le nombre, puis ▫/▫, le nombre devient le numérateur – le curseur est directement au dénominateur.", tasten: '3[▫/▫]4[▶]+1=', ergebnis: '7/4' },
        { text: "Racine : <b>√▫</b>. Il faut ▶ pour que le curseur sorte de la racine : √16 + 9.", tasten: '[√]16[▶]+9=', ergebnis: '13' },
        { text: "Sans ▶, tout reste sous la racine : √(16 + 9).", tasten: '[√]16+9=', ergebnis: '5' },
        { text: "Puissance : <b>x▫</b> place l'exposant en haut ; ▶ te ramène sur la ligne : 2⁵ − 1.", tasten: '2[x^]5[▶]−1=', ergebnis: '31' },
        { text: "Les gabarits peuvent s'imbriquer : (√3 + 1)/2.", tasten: '[▫/▫][√]3[▶]+1[▼]2=', ergebnis: '(1+√3)/2' },
      ],
      merke: "Ouvrir le gabarit → remplir les cases → sortir avec ▶. ▲ et ▼ font passer du numérateur au dénominateur et inversement.",
      falle: "L'erreur la plus fréquente : oublier ▶. Le reste du calcul se retrouve alors au dénominateur, sous la racine ou dans l'exposant.",
      aufgaben: [
        { text: "Calcule 3/8 + 5/12 (résultat sous forme de fraction).", loesung: '[▫/▫]3[▼]8[▶]+[▫/▫]5[▼]12=', anzeige: '19/24' },
        { text: "Calcule √50 − √8.", loesung: '[√]50[▶]−[√]8=', anzeige: '3√2', hinweis: "Après √50, sors de la racine avec ▶ avant de taper −." },
        { text: "Calcule 2³ + 3² avec la touche x▫.", loesung: '2[x^]3[▶]+3[x^]2=', wert: 17 },
        { text: "Calcule le nombre d'or (1 + √5)/2 sous forme de nombre décimal.", loesung: '[▫/▫]1+[√]5[▶][▼]2=[S⇔D]', wert: 1.618033988749895, wertText: '1.618033989' },
      ],
    },
    {
      id: 'brueche',
      gruppe: "Bases",
      titel: "Fractions et fractions mixtes",
      kurz: "Simplifier, fractions mixtes, décimal ↔ fraction, nombres périodiques",
      vorbereitung: STANDARD,
      einleitung: "La calculatrice simplifie les fractions automatiquement et affiche, si possible, les nombres décimaux sous forme de fraction. Les fractions mixtes comme 1½ se saisissent avec <b>SHIFT ▫/▫</b>.",
      schritte: [
        { text: "La simplification se fait toute seule : 12/18 =", tasten: '[▫/▫]12[▼]18=', ergebnis: '2/3' },
        { text: "Fraction mixte : <b>SHIFT ▫/▫</b> ouvre partie entière │ numérateur │ dénominateur. 1½ + 2/3 =", tasten: '[SHIFT][▫/▫]1[▶]1[▼]2[▶]+[▫/▫]2[▼]3=', ergebnis: '13/6', kette: true },
        { text: "<b>SHIFT S⇔D</b> (a b/c ⇔ d/c) transforme la fraction impropre en fraction mixte.", tasten: '[SHIFT][S⇔D]', ergebnis: '2 1/6' },
        { text: "Les nombres décimaux s'affichent sous forme de fraction si celle-ci est assez courte :", tasten: '0.75=', ergebnis: '3/4' },
        { text: "La fx-991DE X affiche les nombres périodiques avec une barre : S⇔D fait passer de 1/7 au nombre décimal périodique.", tasten: '1÷7=[S⇔D]', ergebnis: '0.(142857)' },
        { text: "Saisir une période (seulement sur la fx-991DE X) : après la virgule, <b>ALPHA √▫</b>, puis tape la période. 0,3̄ =", tasten: '0.[ALPHA][√]3=', ergebnis: '1/3' },
      ],
      merke: "S⇔D : fraction ⇔ nombre décimal. SHIFT S⇔D : fraction impropre ⇔ fraction mixte.",
      aufgaben: [
        { text: "Calcule 5/6 − 3/4.", loesung: '[▫/▫]5[▼]6[▶]−[▫/▫]3[▼]4=', anzeige: '1/12' },
        { text: "Calcule 2⅓ · 3/7.", loesung: '[SHIFT][▫/▫]2[▶]1[▼]3[▶]×[▫/▫]3[▼]7=', wert: 1 },
        { text: "Écris 0,125 sous forme de fraction.", loesung: '0.125=', anzeige: '1/8' },
      ],
    },
    {
      id: 'vorrang',
      gruppe: "Bases",
      titel: "Priorités, parenthèses, signe négatif",
      kurz: "Ordre des opérations, (−) ou −, multiplication sans signe",
      vorbereitung: STANDARD,
      einleitung: "La calculatrice calcule toujours dans le même ordre : parenthèses et fonctions, puis puissances, puis signe négatif, puis × et ÷, et enfin + et −. Si tu connais cet ordre, tu as besoin de moins de parenthèses – et tu ne tombes dans aucun piège.",
      schritte: [
        { text: "× et ÷ avant + et − :", tasten: '2+3×4=', ergebnis: '14' },
        { text: "Les parenthèses d'abord :", tasten: '(2+3)×4=', ergebnis: '20' },
        { text: "Le signe négatif <b>(−)</b> est moins prioritaire que le carré : −3² = −9.", tasten: '[(−)]3[x²]=', ergebnis: '-9' },
        { text: "Pour élever −3 au carré, mets-le entre parenthèses : (−3)² = 9.", tasten: '([(−)]3)[x²]=', ergebnis: '9' },
        { text: "Une multiplication <i>sans</i> signe × est prioritaire sur ÷ : la fx-991 calcule 6 ÷ 2(1 + 2) comme 6 ÷ (2 · 3).", tasten: '6÷2(1+2)=', ergebnis: '1' },
        { text: "Les fonctions ouvrent une parenthèse. Ferme-la : sin(30°) + 1 =", tasten: '[sin]30)+1=', ergebnis: '3/2' },
        { text: "Sans ), la calculatrice calcule sin(30 + 1) :", tasten: '[sin]30+1=', ergebnis: '0.5150380749' },
      ],
      merke: "(−) est le signe négatif, − l'opération soustraction. Pour les formules avec un trait de fraction, utilise le gabarit ▫/▫ – ainsi, aucun doute sur l'ordre des calculs.",
      falle: "Pour 1 ÷ 2π, la calculatrice calcule 1 ÷ (2π). Mais si tu écris a ÷ b · c, tu penses peut-être à (a ÷ b) · c – dans le doute, mets des parenthèses !",
      aufgaben: [
        { text: "Calcule (−2)⁴.", loesung: '([(−)]2)[x^]4=', wert: 16 },
        { text: "Calcule −2⁴ (sans parenthèses).", loesung: '[(−)]2[x^]4=', wert: -16 },
        { text: "Calcule (12 − 4)/(2 · 2) avec le gabarit de fraction.", loesung: '[▫/▫]12−4[▼]2×2=', wert: 2 },
      ],
    },
    {
      id: 'potenzen',
      gruppe: "Bases",
      titel: "Puissances, racines, puissances de 10",
      kurz: "x², x▫, x⁻¹, √, ∛, notation scientifique avec ×10ˣ",
      vorbereitung: STANDARD,
      einleitung: "Pour les très grands et les très petits nombres, il y a la touche <b>×10ˣ</b> : 3·10⁸ se tape <b>3 ×10ˣ 8</b>. Les exposants négatifs se saisissent avec <b>(−)</b>.",
      schritte: [
        { text: "Carré :", tasten: '5[x²]=', ergebnis: '25' },
        { text: "Puissance quelconque avec x▫ :", tasten: '2[x^]10=', ergebnis: '1024' },
        { text: "Les racines restent exactes : √2 · √8 =", tasten: '[√]2[▶]×[√]8=', ergebnis: '4' },
        { text: "Racine cubique avec SHIFT √▫ :", tasten: '[SHIFT][√]27=', ergebnis: '3' },
        { text: "Inverse x⁻¹ :", tasten: '4[x⁻¹]=', ergebnis: '1/4' },
        { text: "Année-lumière : 3·10⁸ m/s · 3600 · 24 · 365 s. Les grands résultats s'affichent avec ×10ⁿ.", tasten: '3[×10ˣ]8×3600×24×365=', ergebnis: '9.4608×10^15' },
        { text: "Deux charges élémentaires : 2 · 1,6·10⁻¹⁹ C.", tasten: '1.6[×10ˣ][(−)]19×2=', ergebnis: '3.2×10^-19' },
      ],
      falle: "<b>10 ×10ˣ 3</b> donne 10 · 10³ = 10 000, et non 1000. Pour 10³, tape <b>1 ×10ˣ 3</b> (ou seulement ×10ˣ 3).",
      aufgaben: [
        { text: "Calcule 4,7·10³ · 2,2·10⁻⁶.", loesung: '4.7[×10ˣ]3×2.2[×10ˣ][(−)]6=', wert: 0.01034 },
        { text: "Calcule 2^0,5. Quelle forme exacte la calculatrice affiche-t-elle ?", loesung: '2[x^]0.5=', anzeige: '√2' },
        { text: "Quelle charge portent 5·10¹⁸ électrons ? Q = 5·10¹⁸ · 1,6·10⁻¹⁹ C", loesung: '5[×10ˣ]18×1.6[×10ˣ][(−)]19=', wert: 0.8 },
      ],
    },

    // MARK: Électrotechnique et physique
    {
      id: 'eng',
      gruppe: "Électrotechnique et physique",
      titel: "Touche ENG et symboles ingénieur",
      kurz: "mA, kΩ, µF : résultats avec des exposants multiples de 3",
      vorbereitung: STANDARD,
      einleitung: "En électrotechnique, tu calcules avec k (10³), M (10⁶), m (10⁻³), µ (10⁻⁶), n (10⁻⁹) … La touche <b>ENG</b> affiche chaque résultat avec une puissance de 10 dont l'exposant est un multiple de 3.",
      schritte: [
        { text: "Courant I = U/R avec U = 12 V et R = 4,7 kΩ :", tasten: '12÷4.7[×10ˣ]3=', ergebnis: '3/1175', kette: true },
        { text: "<b>ENG</b> affiche le résultat sous la forme 2,55·10⁻³ A – soit 2,55 mA.", tasten: '[ENG]', ergebnis: '2.553191489×10^-3', kette: true },
        { text: "Encore <b>ENG</b> : l'exposant diminue de 3 (µA). <b>SHIFT ENG</b> (←) va dans l'autre sens.", tasten: '[ENG]', ergebnis: '2553.191489×10^-6' },
        { text: "Activer les symboles ingénieur : <b>SHIFT MENU</b> (SETUP) → 4 (Symbole ingénieur) → 1 (Oui).", tasten: '[SHIFT][MENU]41', kette: true },
        { text: "Tu peux maintenant saisir k, m, µ … avec <b>OPTN 3</b> (Symbole ingénieur ; k est le n° 6) – et le résultat s'affiche avec le symbole :", tasten: '12÷4.7[OPTN]36=[S⇔D]', ergebnis: '2.553191489m' },
        { text: "Montage en parallèle R = (R₁⁻¹ + R₂⁻¹)⁻¹ avec 4,7 kΩ et 10 kΩ :", tasten: '(4.7[OPTN]36[x⁻¹]+10[OPTN]36[x⁻¹])[x⁻¹]=[S⇔D]', ergebnis: '3.197278912k' },
        { text: "Désactiver les symboles ingénieur : SETUP → 4 → 2 (Non).", tasten: '[SHIFT][MENU]42' },
      ],
      merke: "ENG = exposant par pas de 3 (k, M, m, µ). SHIFT ENG décale dans l'autre sens.",
      aufgaben: [
        { text: "Quel courant traverse une résistance de 1,2 kΩ sous 230 V ? (Résultat en A, à lire par ex. avec ENG.)", loesung: '230÷1.2[×10ˣ]3=[ENG]', wert: 230 / 1200, wertText: '191.6666667×10^-3' },
        { text: "Puissance P = U · I avec 5 V et 20 mA.", loesung: '5×20[×10ˣ][(−)]3=', wert: 0.1 },
        { text: "Montage en série : 2,2 kΩ + 470 Ω + 1 kΩ en Ω.", loesung: '2.2[×10ˣ]3+470+1[×10ˣ]3=', wert: 3670 },
      ],
    },
    {
      id: 'speicher',
      gruppe: "Électrotechnique et physique",
      titel: "Ans, variables et mémoire M",
      kurz: "Continuer avec des résultats intermédiaires, STO, RECALL, M+",
      vorbereitung: STANDARD,
      einleitung: "<b>Ans</b> contient toujours le dernier résultat. Dans les variables <b>A–F, x, y</b>, tu enregistres des valeurs durablement (même après avoir éteint la calculatrice). <b>M</b> est une mémoire de cumul.",
      schritte: [
        { text: "D'abord calculer …", tasten: '12×5=', ergebnis: '60', kette: true },
        { text: "… puis continuer simplement avec ÷ : la calculatrice place automatiquement <b>Ans</b> devant.", tasten: '÷4=', ergebnis: '15' },
        { text: "Enregistrer : la valeur, puis <b>STO</b> et la touche de la variable (A se trouve sur (−)). U = 230 V dans A :", tasten: '230[STO][(−)]', ergebnis: '230', kette: true },
        { text: "R = 4,7 kΩ dans B (B se trouve sur °′″) :", tasten: '4.7[×10ˣ]3[STO][°′″]', ergebnis: '4700', kette: true },
        { text: "Utiliser les variables : <b>ALPHA</b> + touche. I = A/B :", tasten: '[ALPHA][(−)]÷[ALPHA][°′″]=', ergebnis: '23/470' },
        { text: "<b>SHIFT STO</b> (RECALL) affiche toutes les valeurs enregistrées. AC ferme la liste.", tasten: '[SHIFT][STO]' },
        { text: "Mémoire de cumul : mettre M à 0 …", tasten: '0[STO][M+]', ergebnis: '0', kette: true },
        { text: "… puis additionner les résultats partiels avec <b>M+</b> : 3 · 4,5 …", tasten: '3×4.5[M+]', ergebnis: '27/2', kette: true },
        { text: "… plus 2 · 1,25 …", tasten: '2×1.25[M+]', ergebnis: '5/2', kette: true },
        { text: "… et rappeler la somme (M est en rouge sur M+) :", tasten: '[ALPHA][M+]=', ergebnis: '16' },
        { text: "<b>=</b> répète le dernier calcul avec le nouvel Ans – idéal pour doubler une valeur, calculer des intérêts ou faire des itérations.", tasten: '1=×2===', ergebnis: '8' },
      ],
      merke: "Ans = dernier résultat. STO + touche enregistre, ALPHA + touche rappelle. M+ additionne, SHIFT M+ (M−) soustrait.",
      aufgaben: [
        { text: "Enregistre r = 0,5 dans A et calcule l'aire du disque A²π.", loesung: '0.5[STO][(−)][ALPHA][(−)][x²][SHIFT][×10ˣ]=', anzeige: '1/4π' },
        { text: "Prix total avec M+ : 3 pièces à 12 €, 5 pièces à 8 €, 2 pièces à 15 €. À la fin, rappelle M.", loesung: '0[STO][M+]3×12[M+]5×8[M+]2×15[M+][ALPHA][M+]=', wert: 106 },
      ],
    },
    {
      id: 'konstanten',
      gruppe: "Électrotechnique et physique",
      titel: "Constantes physiques et conversions",
      kurz: "CONST (SHIFT 7) et CONV (SHIFT 8)",
      vorbereitung: STANDARD,
      einleitung: "<b>SHIFT 7</b> (CONST) contient 47 constantes physiques réparties en 6 groupes, <b>SHIFT 8</b> (CONV) 40 conversions d'unités. Avec CONV, tu tapes d'abord la valeur, puis la conversion.",
      schritte: [
        { text: "Ouvrir CONST : groupes 1 Universelles, 2 Électromagnétiques, 3 Atomiques & nucléaires, 4 Physico-chimiques, 5 Valeurs adoptées, 6 Autres.", tasten: '[SHIFT]7' },
        { text: "Vitesse de la lumière c₀ : groupe 1, n° 3.", tasten: '[SHIFT]713=', ergebnis: '299792458' },
        { text: "Charge élémentaire e : groupe 2, n° 3.", tasten: '[SHIFT]723=', ergebnis: '1.602176634×10^-19' },
        { text: "Poids d'un corps de 75 kg : m · g (g : groupe 5, n° 1). Le résultat s'affiche sous forme de fraction – S⇔D montre le nombre décimal.", tasten: '75×[SHIFT]751=[S⇔D]', ergebnis: '735.49875' },
        { text: "Convertir : 100 km/h en m/s (groupe 5 Vitesse, n° 1).", tasten: '100[SHIFT]851=', ergebnis: '250/9' },
        { text: "25 °C en °F (groupe 9 Température, n° 2).", tasten: '25[SHIFT]892=', ergebnis: '77' },
      ],
      merke: "CONST : groupe, puis numéro. CONV : d'abord la valeur, puis le groupe et la conversion.",
      aufgaben: [
        { text: "Convertis 72 km/h en m/s.", loesung: '72[SHIFT]851=', wert: 20 },
        { text: "Combien de temps la lumière met-elle pour aller du Soleil à la Terre (1,496·10¹¹ m) ? t = s/c₀ en s.", loesung: '1.496[×10ˣ]11÷[SHIFT]713=', wert: 1.496e11 / 299792458, wertText: '499.0118049', tol: 1e-9 },
        { text: "Combien de kW vaut 1 hp (groupe 8 Puissance, n° 1) ?", loesung: '1[SHIFT]881=', wert: 0.745699872 },
      ],
    },
    {
      id: 'trigo',
      gruppe: "Électrotechnique et physique",
      titel: "Trigonométrie et unité d'angle",
      kurz: "Degrés (D) ou radians (R), sin/cos/tan, Pol/Rec",
      vorbereitung: STANDARD,
      einleitung: "En haut de l'écran, tu vois <b>D</b> (degrés), <b>R</b> (radians) ou <b>G</b> (grades). Vérifie-le <i>toujours</i> avant un calcul de trigonométrie ! Pour changer : <b>SHIFT MENU</b> (SETUP) → 2 (Unité d'angle).",
      schritte: [
        { text: "Régler les degrés : SETUP → 2 Unité d'angle → 1 Degré.", tasten: '[SHIFT][MENU]21', kette: true },
        { text: "Valeurs exactes : sin 30° =", tasten: '[sin]30)=', ergebnis: '1/2' },
        { text: "cos 45° =", tasten: '[cos]45)=', ergebnis: '√2/2' },
        { text: "Fonction réciproque avec SHIFT : sin⁻¹(0,5) =", tasten: '[SHIFT][sin]0.5)=', ergebnis: '30' },
        { text: "Piège : en radians (R), sin 30 signifie le sinus de 30 rad !", tasten: '[SHIFT][MENU]22[sin]30)=', ergebnis: '-0.9880316241', kette: true },
        { text: "En radians, on calcule avec π : sin(π/6) =", tasten: '[sin][▫/▫][SHIFT][×10ˣ][▼]6[▶])=', ergebnis: '1/2' },
        { text: "Retour aux degrés. Côté opposé = hypoténuse · sin α : 5 · sin 37°", tasten: '[SHIFT][MENU]21 5×[sin]37)=', ergebnis: '3.009075116', kette: true },
        { text: "<b>Pol</b> (SHIFT +) convertit des coordonnées (x, y) en longueur r et angle θ – comme pour un diagramme de Fresnel.", tasten: '[SHIFT][+]3[SHIFT][)]4)=', ergebnis: 'r=5, θ=53.13010235' },
        { text: "Angle en degrés, minutes, secondes : convertir 1,5° avec °′″.", tasten: '1.5=[°′″]', ergebnis: '1°30\'0"' },
      ],
      falle: "Une mauvaise unité d'angle est l'erreur n° 1 dans les devoirs en classe. Un coup d'œil sur D/R en haut de l'écran fait gagner beaucoup de points.",
      aufgaben: [
        { text: "Triangle rectangle : côté adjacent 8 cm, hypoténuse 10 cm. Combien mesure l'angle (en degrés) ?", loesung: '[SHIFT][MENU]21[SHIFT][cos]8÷10)=', wert: 36.86989764584402, wertText: '36.86989765' },
        { text: "Tension alternative u = 325 V · sin(2π · 50 Hz · 3 ms). Attention : radians !", loesung: '[SHIFT][MENU]22 325[sin]2[SHIFT][×10ˣ]×50×0.003)=', wert: 325 * Math.sin(0.3 * Math.PI), wertText: '262.9305231' },
        { text: "Côté adjacent b = 10 cm · cos 25° (degrés).", loesung: '[SHIFT][MENU]21 10[cos]25)=', wert: 10 * Math.cos(25 * Math.PI / 180), wertText: '9.063077870' },
      ],
    },
    {
      id: 'komplex',
      gruppe: "Électrotechnique et physique",
      titel: "Nombres complexes et phaseurs",
      kurz: "Mode 2 : i, forme polaire r∠φ, module, impédance",
      vorbereitung: STANDARD + '[MENU]2[SHIFT][MENU][▼]21',
      einleitung: "Dans le mode <b>2 Complexes</b>, la touche <b>ENG</b> devient l'unité imaginaire <b>i</b> (en électrotechnique : j). <b>SHIFT ENG</b> donne le symbole d'angle <b>∠</b> pour la forme polaire r∠φ.",
      schritte: [
        { text: "Choisir le mode : MENU → 2 (Complexes).", tasten: '[MENU]2', kette: true },
        { text: "Calculer comme d'habitude : (3 + 4i)(1 − 2i) =", tasten: '(3+4[ENG])(1−2[ENG])=', ergebnis: '11-2i' },
        { text: "Module (longueur du phaseur) avec SHIFT ( (Abs) :", tasten: '[SHIFT][(]3+4[ENG]=', ergebnis: '5' },
        { text: "Angle (argument) avec OPTN → 1 (Argument) :", tasten: '[OPTN]1 3+4[ENG])=', ergebnis: '53.13010235' },
        { text: "Saisir la forme polaire : 230∠30° s'affiche sous forme algébrique a + bi.", tasten: '230[SHIFT][ENG]30=', ergebnis: '199.1858429+115i' },
        { text: "Résultat sous forme polaire : ajoute <b>OPTN ▼ 1</b> (Forme polaire ▸r∠θ) à la fin.", tasten: '3+4[ENG][OPTN][▼]1=', ergebnis: '5∠53.13010235' },
        { text: "Impédance d'un circuit RL série : Z = R + jωL avec R = 100 Ω, L = 0,3 H, f = 50 Hz.", tasten: '100+2[SHIFT][×10ˣ]×50×0.3[ENG][OPTN][▼]1=', ergebnis: '137.414133∠43.30380731' },
        { text: "Courant I = U/Z pour U = 230 V :", tasten: '230÷(100+30[SHIFT][×10ˣ][ENG])=', ergebnis: '1.218049763-1.147984856i' },
      ],
      merke: "ENG = i, SHIFT ENG = ∠. OPTN : Argument, Conjugué, Partie réelle, Partie imaginaire, Forme polaire ▸r∠θ, Forme algébr. ▸a+bi. Dans le SETUP (page 2, Complexe), tu règles l'affichage par défaut a+bi ou r∠θ.",
      aufgaben: [
        { text: "Calcule (2 + 3i) + (4 − i).", loesung: '2+3[ENG]+4−[ENG]=', anzeige: '6+2i' },
        { text: "Calcule le module de −6 + 8i.", loesung: '[SHIFT][(][(−)]6+8[ENG]=', wert: 10 },
        { text: "Saisis le phaseur 10∠90°. Qu'affiche la calculatrice ?", loesung: '10[SHIFT][ENG]90=', anzeige: '10i' },
        { text: "Convertis Z = 50 − 80i en forme polaire.", loesung: '50−80[ENG][OPTN][▼]1=', anzeige: '10√89∠-57.99461679', hinweis: "Le module √8900 = 10√89 reste exact ; S⇔D affiche 94,34∠−57,99." },
      ],
    },

    // MARK: Outils
    {
      id: 'calc',
      gruppe: "Outils",
      titel: "Formules avec CALC, équations avec SOLVE",
      kurz: "Taper la formule une fois, remplacer les valeurs, isoler n'importe quelle grandeur",
      vorbereitung: STANDARD,
      einleitung: "<b>CALC</b> demande la valeur de chaque variable, l'une après l'autre, puis calcule la formule – pratique pour une série de mesures. <b>SOLVE</b> (SHIFT CALC) résout une équation par rapport à une variable (méthode de Newton avec une valeur initiale). Le signe égal s'obtient avec <b>ALPHA CALC</b>.",
      schritte: [
        { text: "P = U²/R : tape la formule avec A (= U) et B (= R), puis <b>CALC</b>, et saisis les valeurs (chacune suivie de =).", tasten: '[▫/▫][ALPHA][(−)][x²][▼][ALPHA][°′″][CALC]230=1000=', ergebnis: '529/10', kette: true },
        { text: "Encore <b>CALC</b> – nouvelles valeurs, même formule : 12 V aux bornes de 4,7 Ω.", tasten: '[CALC]12=4.7=', ergebnis: '1440/47' },
        { text: "SOLVE : x² − 5x + 6 = 0 avec la valeur initiale 0. Le « = » s'obtient avec ALPHA CALC. Après SHIFT CALC : tape la valeur initiale, =, puis encore = pour résoudre.", tasten: '[x][x²]−5[x]+6[ALPHA][CALC]0[SHIFT][CALC]0==', ergebnis: 'x=2;G−D=0', kette: true },
        { text: "Tu trouves la deuxième solution avec une autre valeur initiale (5).", tasten: '[SHIFT][CALC]5==', ergebnis: 'x=3;G−D=0' },
        { text: "Isoler une grandeur sans algèbre : quelle résistance absorbe exactement 60 W sous 230 V ? Deux fois AC pour quitter SOLVE. Ensuite 60 = 230²/B, valeur initiale 100.", tasten: '[AC][AC]60[ALPHA][CALC][▫/▫]230[x²][▼][ALPHA][°′″][SHIFT][CALC]100==', ergebnis: 'B=881.6666667;G−D=0' },
      ],
      merke: "CALC : remplacer par des valeurs (▼ saute une variable). SOLVE : saisir la valeur initiale, puis =. G−D = 0 (gauche moins droite) signifie : la solution est juste.",
      falle: "SOLVE ne trouve jamais qu'<i>une seule</i> solution – celle qui est la plus proche de la valeur initiale. Pour trouver d'autres solutions, change la valeur initiale.",
      aufgaben: [
        { text: "Avec CALC, calcule l'aire du disque πx² pour x = 3.", loesung: '[SHIFT][×10ˣ][x][x²][CALC]3=', anzeige: '9π' },
        { text: "U = R · I : avec CALC, calcule la tension pour R = 470 Ω et I = 0,02 A (formule A·B).", loesung: '[ALPHA][(−)][ALPHA][°′″][CALC]470=0.02=', wert: 9.4 },
        { text: "Résous 2ˣ = 10 avec SOLVE (valeur initiale 1).", loesung: '2[x^][x][▶][ALPHA][CALC]10[SHIFT][CALC]1==', variable: 'x', wert: Math.log2(10), wertText: '3.321928095' },
      ],
    },
    {
      id: 'gleichungen',
      gruppe: "Outils",
      titel: "Systèmes d'équations et polynômes",
      kurz: "Mode A : systèmes jusqu'à 4 inconnues, équations du 2e et du 3e degré",
      vorbereitung: STANDARD,
      einleitung: "Dans le mode <b>A Équations</b> (MENU, puis la touche (−) pour A), tu ne saisis que les coefficients. <b>1</b> = Système linéaire, <b>2</b> = Polynôme. Valide chaque valeur avec = ; un = de plus lance la résolution, et chaque = suivant affiche la solution suivante.",
      schritte: [
        { text: "x + 2y = 3 et 2x + 3y = 4 : MENU A → 1 (Système linéaire) → 2 inconnues, coefficients ligne par ligne.", tasten: '[MENU][(−)]12 1=2=3=2=3=4==', ergebnis: 'x=-1', kette: true },
        { text: "Avec = (ou ▼), passe à la solution suivante :", tasten: '=', ergebnis: 'y=2' },
        { text: "Lois de Kirchhoff : I₁ − I₂ − I₃ = 0, 100I₁ + 220I₂ = 12, 220I₂ − 330I₃ = 0 (3 inconnues ; x = I₁).", tasten: '[MENU][(−)]13 1=[(−)]1=[(−)]1=0=100=220=0=12=0=220=[(−)]330=0==', ergebnis: 'x=3/58' },
        { text: "Équation du second degré x² + 2x − 2 = 0 : MENU A → 2 (Polynôme) → degré 2.", tasten: '[MENU][(−)]22 1=2=[(−)]2==', ergebnis: 'x₁=-1+√3', kette: true },
        { text: "Deuxième solution, puis le sommet de la parabole (x et y du minimum) :", tasten: '=', ergebnis: 'x₂=-1-√3' },
        { text: "Équation du troisième degré x³ − 6x² + 11x − 6 = 0 :", tasten: '[MENU][(−)]23 1=[(−)]6=11=[(−)]6==', ergebnis: 'x₁=3' },
        { text: "Pas de solution réelle ? Alors la calculatrice affiche les solutions complexes : x² + 1 = 0.", tasten: '[MENU][(−)]22 1=0=1==', ergebnis: 'x₁=i' },
      ],
      merke: "Mets d'abord l'équation sous la forme … = 0 et saisis 0 pour les termes manquants. Dans l'éditeur, AC remet tous les coefficients à 0.",
      aufgaben: [
        { text: "Résous 2x − y = 1 et x + y = 5. Combien vaut x ?", loesung: '[MENU][(−)]12 2=[(−)]1=1=1=1=5==', anzeige: 'x=2' },
        { text: "Résous 2x² − 3x − 2 = 0. Combien vaut x₁ ?", loesung: '[MENU][(−)]22 2=[(−)]3=[(−)]2==', anzeige: 'x₁=2' },
        { text: "Sommet de la parabole y = x² − 6x + 5 : quelle est la valeur de y au minimum ?", loesung: '[MENU][(−)]22 1=[(−)]6=5=====', anzeige: 'y=-4' },
      ],
    },
    {
      id: 'tabelle',
      gruppe: "Outils",
      titel: "Tableaux de valeurs",
      kurz: "Mode 9 : f(x) et g(x), début, fin, pas",
      vorbereitung: STANDARD,
      einleitung: "Dans le mode <b>9 Tableau</b>, tu tapes f(x) (x avec la touche <b>x</b>), si tu veux aussi g(x), puis le début, la fin et le pas. Avec ▲▼, tu te déplaces dans le tableau ; dans la colonne x, tu peux remplacer des valeurs.",
      schritte: [
        { text: "f(x) = x² − 2x − 3 de −2 à 4 : tape f, =, laisse g vide (=), puis Début −2, Fin 4, Pas 1 et encore =.", tasten: '[MENU]9[x][x²]−2[x]−3==[(−)]2=4=1==' },
        { text: "Où f change-t-elle de signe ? Descends avec ▼ : zéros en x = −1 et x = 3.", tasten: '[▼][▼][▼][▼][▼]' },
        { text: "Comparer deux fonctions : f(x) = x², g(x) = 2x + 3. Mêmes valeurs pour x = 3.", tasten: '[MENU]9[x][x²]=2[x]+3=0=4=1==' },
      ],
      merke: "AC ramène à la saisie des fonctions. Le tableau a au maximum 30 lignes (avec g) ou 45 lignes (f seule).",
      aufgaben: [
        { text: "Calcule f(1,5) pour f(x) = x² − 2x − 3 avec CALC dans le mode Calculs.", loesung: '[MENU]1[x][x²]−2[x]−3[CALC]1.5=', wert: -3.75 },
      ],
    },
    {
      id: 'statistik',
      gruppe: "Outils",
      titel: "Statistiques et régression",
      kurz: "Mode 6 : moyenne, écart-type, droite de régression",
      vorbereitung: STANDARD,
      einleitung: "Dans le mode <b>6 Statistiques</b>, tu choisis le type (1 = une variable, 2 = y = a + bx …) et tu tapes les données dans l'éditeur (chaque fois =). <b>AC</b> mène à l'écran de calcul, <b>OPTN</b> aux paramètres statistiques.",
      schritte: [
        { text: "Cinq valeurs mesurées : 4,8 / 5,1 / 5,0 / 4,9 / 5,2 V.", tasten: '[MENU]61 4.8=5.1=5=4.9=5.2=', kette: true },
        { text: "<b>AC</b>, puis <b>OPTN 2</b> (Calcul 1 variable) affiche tous les paramètres (▲▼ pour faire défiler).", tasten: '[AC][OPTN]2', ergebnis: 'x̄=5;Σx=25;Σx²=125.1;σ²x=0.02' },
        { text: "Récupérer une seule valeur pour un calcul : OPTN ▼ 2 (Variables) → 4 = σx (écart-type).", tasten: '[AC][OPTN][▼]24=', ergebnis: '0.1414213562' },
        { text: "Régression : caractéristique U-I d'une résistance. Type 2 (y = a + bx), x = U, y = I.", tasten: '[MENU]62 2=4=6=8=[▶][▲][▲][▲][▲]0.0042=0.0085=0.0128=0.017=', kette: true },
        { text: "Pente b = I/U avec OPTN ▼ 4 (Régression) → 2 (b) :", tasten: '[AC][OPTN][▼]42=[S⇔D]', ergebnis: '2.135×10^-3', kette: true },
        { text: "La résistance est l'inverse de la pente : R = 1/b.", tasten: '[x⁻¹]=[S⇔D]', ergebnis: '468.3840749' },
      ],
      merke: "σx : écart-type des valeurs mesurées (population), sx : écart-type de l'échantillon. Pour une régression, r indique la qualité de l'ajustement (|r| proche de 1 = très bon).",
      aufgaben: [
        { text: "Moyenne de 12, 15, 11, 14, 13 ?", loesung: '[MENU]61 12=15=11=14=13=[AC][OPTN][▼]22=', wert: 13 },
        { text: "Écart-type de l'échantillon sx pour les mêmes données (OPTN ▼ 2 → 6) ?", loesung: '[MENU]61 12=15=11=14=13=[AC][OPTN][▼]26=', wert: Math.sqrt(2.5), wertText: '1.58113883' },
      ],
    },
    {
      id: 'analysis',
      gruppe: "Outils",
      titel: "Intégrale, dérivée, somme",
      kurz: "∫, d/dx et Σ – numérique et rapide",
      vorbereitung: STANDARD,
      einleitung: "La touche <b>∫▫▫</b> calcule des intégrales définies, <b>SHIFT ∫</b> (d/dx) la dérivée en un point, <b>SHIFT x</b> (Σ) des sommes. Ordre des cases : fonction → borne inférieure → borne supérieure (▶ pour passer à la case suivante).",
      schritte: [
        { text: "∫₀² x² dx :", tasten: '[∫][x][x²][▶]0[▶]2=', ergebnis: '8/3' },
        { text: "Aire sous une arche de sinusoïde de 0 à π – avec les fonctions trigonométriques, toujours en <b>radians</b> !", tasten: '[SHIFT][MENU]22[∫][sin][x])[▶]0[▶][SHIFT][×10ˣ]=', ergebnis: '2' },
        { text: "Dérivée de x³ en x = 2 (d/dx = SHIFT ∫) :", tasten: '[SHIFT][MENU]21[SHIFT][∫][x][x^]3[▶][▶]2=', ergebnis: '12' },
        { text: "Somme 1 + 2 + … + 10 avec Σ (SHIFT x) :", tasten: '[SHIFT][x][x][▶]1[▶]10=', ergebnis: '55' },
      ],
      falle: "N'utilise sin, cos, tan dans ∫ et d/dx qu'en radians (R) – sinon les résultats sont faux.",
      aufgaben: [
        { text: "Calcule ∫₁³ (2x + 1) dx.", loesung: '[∫]2[x]+1[▶]1[▶]3=', wert: 10 },
        { text: "Combien vaut la dérivée de √x en x = 4 ?", loesung: '[SHIFT][∫][√][x][▶][▶]4=', wert: 0.25 },
        { text: "Valeur efficace d'une tension sinusoïdale de valeur crête û = 325 V : U = √( 1/(2π) · ∫₀^2π (325 sin x)² dx ) (radians).", loesung: '[SHIFT][MENU]22[√][▫/▫]1[▼]2[SHIFT][×10ˣ][▶][∫](325[sin][x]))[x²][▶]0[▶]2[SHIFT][×10ˣ]=', wert: 325 / Math.SQRT2, wertText: '229.8097039', tol: 1e-8 },
      ],
    },
    {
      id: 'basisn',
      gruppe: "Outils",
      titel: "Systèmes de numération (électronique numérique)",
      kurz: "Mode 3 : DEC, HEX, BIN, OCT, and/or/not",
      vorbereitung: STANDARD,
      einleitung: "Dans le mode <b>3 Base N</b>, tu calcules avec des nombres entiers (32 bits). Ici, ce sont les inscriptions bleues qui comptent : <b>x²</b> = DEC, <b>x▫</b> = HEX, <b>log</b> = BIN, <b>ln</b> = OCT. Les chiffres hexadécimaux A–F se trouvent sur les touches (−) à tan.",
      schritte: [
        { text: "Choisir le mode 3 (démarre en DEC).", tasten: '[MENU]3', kette: true },
        { text: "Saisir 255 …", tasten: '255=', ergebnis: '255', kette: true },
        { text: "… et l'afficher en hexadécimal avec HEX (touche x▫) :", tasten: '[x^]', ergebnis: '000000FF' },
        { text: "Calculer en binaire : BIN (touche log), puis 1011 + 110.", tasten: '[log]1011+110=', ergebnis: '0000 0000 0000 0000/0000 0000 0001 0001', kette: true },
        { text: "ET logique avec OPTN → 1 (and) : 1100 and 1010.", tasten: '1100[OPTN]1 1010=', ergebnis: '0000 0000 0000 0000/0000 0000 0000 1000', kette: true },
        { text: "Afficher en décimal (touche x²) :", tasten: '[x²]', ergebnis: '8' },
      ],
      merke: "Tu peux changer de système de numération à tout moment avec les touches bleues – même pour le résultat affiché.",
      aufgaben: [
        { text: "Comment s'écrit 200 (décimal) en hexadécimal ?", loesung: '[MENU]3[x²]200=[x^]', anzeige: '000000C8' },
        { text: "Quel nombre décimal correspond à 1111 (binaire) ?", loesung: '[MENU]3[log]1111=[x²]', wert: 15 },
      ],
    },
    {
      id: 'fehler',
      gruppe: "Outils",
      titel: "Détective des erreurs",
      kurz: "Math ERROR, Syntax ERROR, mauvaise unité d'angle, Fix, RESET",
      vorbereitung: STANDARD,
      einleitung: "Un message d'erreur, ce n'est pas un drame : <b>AC</b> efface, <b>◀</b> ou <b>▶</b> te ramène à la saisie pour que tu puisses corriger.",
      schritte: [
        { text: "<b>Math ERROR</b> : division par 0, racine carrée d'un nombre négatif, résultat trop grand …", tasten: '5÷0=', ergebnis: 'Math ERROR' },
        { text: "<b>Syntax ERROR</b> : la saisie n'est pas une expression valable, par ex. deux signes d'opération à la suite.", tasten: '5×÷2=', ergebnis: 'Syntax ERROR', kette: true },
        { text: "Avec ◀, retourne à la saisie, supprime l'erreur avec DEL et recalcule.", tasten: '[◀][◀][◀][DEL][▶][▶]=', ergebnis: '5/2', kette: true },
        { text: "Des valeurs trigonométriques bizarres ? Vérifie l'unité d'angle ! Ici, la calculatrice est en R :", tasten: '[SHIFT][MENU]22[sin]30)=', ergebnis: '-0.9880316241' },
        { text: "Trop peu de décimales ? Fix est peut-être réglé (FIX en haut de l'écran). Fix 2 :", tasten: '[SHIFT][MENU]21[SHIFT][MENU]312 1÷3[SHIFT]=', ergebnis: '0.33', kette: true },
        { text: "Retour à Norm 1 : SETUP → 3 (Format nombre) → 3 (Norm) → 1.", tasten: '[SHIFT][MENU]331 1÷3[SHIFT]=', ergebnis: '0.3333333333' },
        { text: "Quand plus rien ne marche : <b>SHIFT 9</b> (RESET) → 3 Tout initialiser → = → AC.", tasten: '[SHIFT]93=[AC]' },
      ],
      merke: "Avant chaque devoir en classe, vérifie rapidement : mode 1 (Calculs), D en haut de l'écran, pas de FIX/SCI.",
      aufgaben: [
        { text: "Un camarade tape sin 30 + 15 sans fermer la parenthèse. Qu'affiche la calculatrice (en degrés) ?", loesung: '[sin]30+15=', anzeige: '√2/2', hinweis: "Sans ), la calculatrice calcule sin(30 + 15) = sin 45°." },
        { text: "Quelqu'un veut calculer 1/(2 · 5) et tape 1 ÷ 2 × 5. Calcule la bonne valeur avec le gabarit de fraction.", loesung: '[▫/▫]1[▼]2×5=', wert: 0.1 },
      ],
    },
  ],

  // MARK: Aide touches

  tasten: {
    shift: { name: 'SHIFT', haupt: `Active l'inscription <b style="color:#b8860b">jaune</b> de la touche suivante. Un <b>S</b> apparaît à l'écran. Appuyer encore une fois annule SHIFT.` },
    alpha: { name: 'ALPHA', haupt: `Active l'inscription <b style="color:#c8102e">rouge</b> de la touche suivante : variables A–F, x, y, M ainsi que =, : et i. Un <b>A</b> apparaît à l'écran.` },
    menu: { name: 'MENU', haupt: "Menu principal avec toutes les applications (1 Calculs … D Proportions). Choisis avec la touche chiffre/lettre ou avec les flèches et =.", shift: "<b>SETUP</b> : réglages – Entrée/Sortie, Unité d'angle, Format nombre, Symbole ingénieur, Résultat fraction, Complexe, Séparateur déc. … (▼ pour la page suivante)." },
    on: { name: 'ON', haupt: "Allume la calculatrice. Efface l'écran et l'historique ; les variables et les réglages sont conservés." },
    up: { name: '▲', haupt: "Dans une fraction : du dénominateur au numérateur. Sans saisie : remonte dans l'historique vers les calculs précédents. Dans les menus et les listes : vers le haut." },
    down: { name: '▼', haupt: "Dans une fraction : du numérateur au dénominateur. Dans l'historique : vers l'avant. Dans les menus : page suivante ; dans les listes : vers le bas." },
    left: { name: '◀', haupt: "Curseur vers la gauche. Après un résultat : modifier le dernier calcul (curseur à la fin)." },
    right: { name: '▶', haupt: "Curseur vers la droite – et <b>sortie d'un gabarit</b> (fraction, racine, puissance). Après un résultat : modifier le calcul (curseur au début)." },
    optn: { name: 'OPTN', haupt: "Fonctions supplémentaires de l'application en cours, par ex. dans Calculs : Fonct. hyperbol., Unité d'angle (°, r, g), Symbole ingénieur (k, m, µ …). Dans Complexes : Argument, Conjugué, ▸r∠θ. Dans Statistiques : paramètres statistiques.", shift: "<b>QR</b> : affiche à l'écran le code QR de ce simulateur (sur la vraie calculatrice : lien vers le site web de CASIO)." },
    calc: { name: 'CALC', haupt: "Évalue une formule avec des variables : demande chaque variable (valeur, =), puis calcule. Encore CALC pour de nouvelles valeurs.", shift: "<b>SOLVE</b> : résout une équation par rapport à une variable (saisir la valeur initiale, puis =).", alpha: "<b>=</b> comme signe égal dans les équations (pour SOLVE, CALC, Vérification)." },
    int: { name: '∫▫▫', haupt: "Intégrale définie : fonction, borne inférieure et borne supérieure (▶ pour passer à la case suivante).", shift: "<b>d/dx</b> : dérivée d'une fonction en un point.", alpha: "<b>:</b> sépare plusieurs calculs, exécutés l'un après l'autre avec =." },
    x: { name: 'x', haupt: "La variable x (pour les fonctions, CALC, SOLVE, les tableaux).", shift: "<b>Σ</b> : somme d'une expression en x, d'une valeur de début à une valeur de fin." },
    frac: { name: '▫/▫', haupt: "Gabarit de fraction. Si un nombre est tapé juste avant, il devient le numérateur.", shift: "Fraction mixte (partie entière, numérateur, dénominateur)." },
    sqrt: { name: '√▫', haupt: "Racine carrée. Avec ▶, tu sors de la racine.", shift: "∛ : racine cubique.", alpha: "Saisir la période d'un nombre décimal (fx-991DE X), par ex. 0,1 puis ALPHA √ 6 pour 0,16̄." },
    sq: { name: 'x²', haupt: "Carré de la valeur précédente.", shift: "x³ : cube (puissance 3).", extra: "En mode Base N (bleu) : <b>DEC</b>, système décimal." },
    pow: { name: 'x▫', haupt: "Puissance quelconque : l'exposant se saisit en haut (▶ pour revenir).", shift: "▫√▫ : racine n-ième.", extra: "Base N : <b>HEX</b>." },
    log: { name: 'log▫▫', haupt: "Logarithme de base quelconque : log₂(16) = 4.", shift: "10▫ : puissance de 10, 10ˣ.", extra: "Base N : <b>BIN</b>." },
    ln: { name: 'ln', haupt: "Logarithme népérien (base e).", shift: "e▫ : fonction exponentielle eˣ.", extra: "Base N : <b>OCT</b>." },
    neg: { name: '(−)', haupt: "Signe négatif (pas la touche moins !). −3² = −9, mais (−3)² = 9.", shift: "<b>log(</b> : logarithme décimal ; avec un séparateur, aussi log(a; b) en base a.", alpha: "Variable <b>A</b>.", extra: "Base N (HEX) : chiffre A." },
    dms: { name: '°′″', haupt: "Saisir des degrés, minutes, secondes (appuyer après chaque partie). Appliquée à un résultat : conversion décimal ⇔ °′″.", shift: "<b>FACT</b> : décomposition du résultat en facteurs premiers.", alpha: "Variable <b>B</b>." },
    inv: { name: 'x⁻¹', haupt: "Inverse 1/x. Pour les matrices : matrice inverse.", shift: "x! : factorielle.", alpha: "Variable <b>C</b>." },
    sin: { name: 'sin', haupt: "Sinus – attention à l'unité d'angle D/R/G !", shift: "sin⁻¹ (arcsin) : angle correspondant à une valeur de sinus.", alpha: "Variable <b>D</b>." },
    cos: { name: 'cos', haupt: "Cosinus.", shift: "cos⁻¹ (arccos).", alpha: "Variable <b>E</b>." },
    tan: { name: 'tan', haupt: "Tangente.", shift: "tan⁻¹ (arctan).", alpha: "Variable <b>F</b>." },
    sto: { name: 'STO', haupt: "Enregistre une valeur (ou un résultat) dans une variable – STO, puis la touche de la variable (sans ALPHA).", shift: "<b>RECALL</b> : affiche toutes les variables ; une touche de variable l'insère dans le calcul." },
    eng: { name: 'ENG', haupt: "Résultat en notation ingénieur (exposant multiple de 3) ; appuyer encore décale de 10³.", shift: "← : notation ingénieur dans l'autre sens. En mode Complexes : <b>∠</b> (forme polaire).", extra: "En mode Complexes, ENG est l'unité imaginaire <b>i</b>." },
    lpar: { name: '(', haupt: "Parenthèse ouvrante.", shift: "<b>Abs</b> : valeur absolue |▫|." },
    rpar: { name: ')', haupt: "Parenthèse fermante (ferme aussi sin(, log( …).", shift: "Séparateur pour les fonctions à plusieurs valeurs, par ex. Pol(3; 4) (avec le point décimal : virgule).", alpha: "Variable <b>x</b>." },
    sd: { name: 'S⇔D', haupt: "Bascule le résultat : exact (fraction, racine, π) ⇔ nombre décimal (sur la DE X, aussi périodique).", shift: "a b/c ⇔ d/c : fraction mixte ⇔ fraction impropre.", alpha: "Variable <b>y</b>." },
    mplus: { name: 'M+', haupt: "Ajoute le résultat à la mémoire M (M apparaît en haut).", shift: "M− : soustrait de la mémoire M.", alpha: "Mémoire <b>M</b> comme variable." },
    7: { name: '7', haupt: "Chiffre 7.", shift: "<b>CONST</b> : 47 constantes physiques." },
    8: { name: '8', haupt: "Chiffre 8.", shift: "<b>CONV</b> : 40 conversions d'unités." },
    9: { name: '9', haupt: "Chiffre 9.", shift: "<b>RESET</b> : réinitialiser les réglages, les variables/la mémoire ou tout." },
    del: { name: 'DEL', haupt: "Efface le caractère à gauche du curseur.", shift: "<b>INS</b> : le gabarit suivant englobe l'expression à droite du curseur.", alpha: "<b>UNDO</b> : annule la dernière modification." },
    ac: { name: 'AC', haupt: "Efface toute la saisie, ou ferme les menus et les messages d'erreur.", shift: "<b>OFF</b> : éteint la calculatrice (la mémoire est conservée)." },
    mul: { name: '×', haupt: "Multiplication.", shift: "<b>nPr</b> : arrangements (permutations)." },
    div: { name: '÷', haupt: "Division.", shift: "<b>nCr</b> : combinaisons (coefficient binomial)." },
    add: { name: '+', haupt: "Addition.", shift: "<b>Pol(x; y)</b> : cartésien → polaire (r, θ)." },
    sub: { name: '−', haupt: "Soustraction (pour les nombres négatifs, prends la touche (−)).", shift: "<b>Rec(r; θ)</b> : polaire → cartésien (x, y)." },
    0: { name: '0', haupt: "Chiffre 0.", shift: "<b>Rnd(</b> : arrondit selon le format de nombre réglé (Fix/Sci)." },
    dot: { name: "Séparateur décimal", haupt: "Virgule ou point (SETUP → Séparateur déc.).", shift: "<b>Ran#</b> : nombre aléatoire de 0,000 à 0,999.", alpha: "<b>RanInt#(a; b)</b> : nombre entier aléatoire de a à b (dé : 1; 6)." },
    exp: { name: '×10ˣ', haupt: "Puissance de 10 pour la notation scientifique : 1,6 ×10ˣ (−) 19.", shift: '<b>π</b>', alpha: "<b>e</b> (nombre d'Euler)" },
    ans: { name: 'Ans', haupt: "Le dernier résultat.", shift: "<b>%</b> : pourcentage (150 × 20 % = 30)." },
    eq: { name: '=', haupt: "Exécute le calcul. Encore = répète le dernier calcul avec le nouvel Ans.", shift: "<b>≈</b> : résultat directement sous forme de nombre décimal." },
  },

  // MARK: Astuces

  tipps: [
    { titel: "Ans arrive tout seul", text: "Après un résultat, chaque opération (+ − × ÷ x² …) commence automatiquement par Ans. Tu n'as donc pas besoin de taper Ans.", tasten: '20=÷4=' },
    { titel: "= répète", text: "Quand un résultat est affiché, = répète le dernier calcul avec le nouvel Ans – pratique pour les intérêts composés ou les itérations.", tasten: '1000=×1.05===' },
    { titel: "Modifier au lieu de retaper", text: "Avec ◀, tu rappelles le dernier calcul, avec ▲ les plus anciens. Tu modifies, tu appuies sur = – et c'est fini." },
    { titel: "Directement en nombre décimal", text: "SHIFT = (≈) affiche tout de suite le résultat sous forme de nombre décimal ; S⇔D bascule à tout moment.", tasten: '1÷3[SHIFT]=' },
    { titel: "Fermer les parenthèses", text: "sin(, cos(, log( … ouvrent une parenthèse. Si tu oublies ), tout le reste du calcul fait partie de l'argument." },
    { titel: "Gabarit de fraction pour les formules", text: "Pour les formules avec un trait de fraction (par ex. R = U/I, montage en parallèle), utilise le gabarit ▫/▫ – ainsi, l'ordre des calculs est toujours juste." },
    { titel: "D ou R ?", text: "La lettre en haut de l'écran indique l'unité d'angle : D = degrés, R = radians. Pour ∫ et d/dx avec des fonctions trigonométriques, règle R." },
    { titel: "Plusieurs calculs d'un coup", text: "ALPHA ∫ donne un deux-points. Chaque = affiche le résultat partiel suivant (Disp en haut de l'écran).", tasten: '3+3[ALPHA][∫]3×3==' },
    { titel: "Annuler", text: "ALPHA DEL (UNDO) annule la dernière modification de la saisie." },
    { titel: "Sur l'ordinateur", text: "Clavier : chiffres, + − * / ^ ( ), Entrée = « = », Retour arrière = DEL, Échap = AC, flèches. Q affiche le code QR en plein écran." },
    { titel: "Installer comme appli", text: "iPhone/iPad : dans Safari, Partager → « Sur l'écran d'accueil ». Android : menu → « Installer l'application ». Ensuite, le simulateur fonctionne aussi hors ligne." },
  ],

  ueber: `<h2>fx-991DE X Trainer</h2>
<p>Simulateur de calculatrice pour les cours, inspiré de la calculatrice scientifique <b>CASIO fx-991DE X</b> (ClassWiz) : mêmes touches aux mêmes places, saisie naturelle comme dans le manuel et résultats exacts – pour que tu puisses t'entraîner à utiliser ta calculatrice aussi sur ton smartphone ou au projecteur.</p>
<p>Inclus : Calculs, Complexes, Base N, Matrices, Vecteurs, Statistiques, Distributions, Tableau, Équations, Inéquations, Vérification et Proportions. Non inclus : Tableur.</p>
<p class="gedaempft">Un projet pédagogique de <b>Tom Bleyer</b> (LTEtt, électrotechnique). Ce n'est pas un produit CASIO. CASIO, ClassWiz et fx-991 sont des marques de CASIO Computer Co., Ltd. Dans certains cas, les résultats peuvent différer de l'affichage de la vraie calculatrice.</p>
<p class="gedaempft">Code source (licence MIT) : <a href="https://github.com/temmchen/fx991">github.com/temmchen/fx991</a></p>`,
};
